### ISSUE TITLE
compile erro!

### ISSUE THREAD

**Issue by zhangdaolong** [intel/compute-runtime#100]
# scl enable devtoolset-4 llvm-toolset-7 "make -j `nproc` package"
[  2%] Built target gmm_umd
[  3%] Built target igfxgmmumd
[  4%] Built target igfx_gmmumd_dll
[  5%] Built target igfx_gmmumd_excite
[  5%] Built target gmock-gtest
[  5%] Built target elflib
[  5%] Built target igdrcl_lib_release_sharings_enable
[  9%] Built target biksim
[  9%] Built target cclang
[  9%] Built target LLVMDemangle
[ 10%] Built target LLVMTableGen
[ 11%] Built target obj.llvm-tblgen
[ 11%] Built target check_headers
[ 11%] Built target LLVMMCParser
[ 15%] Built target LLVMSupport
[ 15%] Building custom target for Metadata Framework
[ 15%] Tablegenning GenISAIntrinsics.
[ 17%] Built target LLVMMC
[ 17%] Built target MDAutogen
[ 17%] Built target GenISAIntrinsicsTablegen
[ 17%] Built target builtins_sources
[ 18%] Built target IGA_OLIB
[ 20%] Built target GEDLibrary
[ 22%] Built target SPIRV-Tools
[ 22%] Built target igdrcl_lib_mockable_sharings_enable
[ 23%] Built target igdrcl_mocks
[ 23%] Built target igdrcl_libult_cs
[ 24%] Built target igdrcl_libult
[ 24%] Built target test_dynamic_lib
[ 24%] Built target mock_gmm
[ 24%] Built target igdrcl_libult_env
[ 24%] Built target elflib_tests
[ 24%] Built target cloc_segfault_test
[ 25%] Built target cloc_tests
[ 27%] Built target GMMULT
[ 27%] Built target GetClang
[ 28%] Built target cloc
[ 28%] Linking CXX executable ../../bin/llvm-tblgen
[ 28%] Built target LocalScheduler
[ 28%] Built target IGA_SLIB
Scanning dependencies of target IGA_ENC_LIB
[ 36%] Built target igdrcl_lib_mockable
Scanning dependencies of target IGA_DLL
[ 36%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_DLL.dir/api/iga.cpp.o
[ 36%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/api/igaEncoderWrapper.cpp.o
[ 43%] Built target igdrcl_lib_release
Scanning dependencies of target igdrcl_linux_dll_tests
../../lib/libLLVMTableGen.a(Main.cpp.o): In function `llvm::TableGenMain(char*, bool (*)(llvm::raw_ostream&, llvm::RecordKeeper&))':
Main.cpp:(.text._ZN4llvm12TableGenMainEPcPFbRNS_11raw_ostreamERNS_12RecordKeeperEE+0x24e): undefined reference to `std::system_category()'
../../lib/libLLVMSupport.a(MemoryBuffer.cpp.o): In function `getMemoryBufferForStream(int, llvm::Twine const&)':
MemoryBuffer.cpp:(.text._ZL24getMemoryBufferForStreamiRKN4llvm5TwineE+0x10a): undefined reference to `std::generic_category()'
../../lib/libLLVMSupport.a(MemoryBuffer.cpp.o): In function `getOpenFileImpl(int, llvm::Twine const&, unsigned long, unsigned long, long, bool, bool)':
MemoryBuffer.cpp:(.text._ZL15getOpenFileImpliRKN4llvm5TwineEmmlbb+0x10c): undefined reference to `std::generic_category()'
MemoryBuffer.cpp:(.text._ZL15getOpenFileImpliRKN4llvm5TwineEmmlbb+0x251): undefined reference to `std::system_category()'
MemoryBuffer.cpp:(.text._ZL15getOpenFileImpliRKN4llvm5TwineEmmlbb+0x3ec): undefined reference to `std::generic_category()'
../../lib/libLLVMSupport.a(raw_ostream.cpp.o): In function `llvm::raw_fd_ostream::raw_fd_ostream(llvm::StringRef, std::error_code&, llvm::sys::fs::OpenFlags)':
raw_ostream.cpp:(.text._ZN4llvm14raw_fd_ostreamC2ENS_9StringRefERSt10error_codeNS_3sys2fs9OpenFlagsE+0x7b): undefined reference to `std::system_category()'
../../lib/libLLVMSupport.a(raw_ostream.cpp.o): In function `llvm::outs()':
raw_ostream.cpp:(.text._ZN4llvm4outsEv+0xd): undefined reference to `std::system_category()'
../../lib/libLLVMSupport.a(Path.cpp.o): In function `llvm::sys::fs::create_directory(llvm::Twine const&, bool, llvm::sys::fs::perms)':
Path.cpp:(.text._ZN4llvm3sys2fs16create_directoryERKNS_5TwineEbNS1_5permsE+0x46): undefined reference to `std::system_category()'
Path.cpp:(.text._ZN4llvm3sys2fs16create_directoryERKNS_5TwineEbNS1_5permsE+0x85): undefined reference to `std::generic_category()'
../../lib/libLLVMSupport.a(Path.cpp.o): In function `llvm::sys::fs::remove(llvm::Twine const&, bool)':
Path.cpp:(.text._ZN4llvm3sys2fs6removeERKNS_5TwineEb+0x6d): undefined reference to `std::generic_category()'
Path.cpp:(.text._ZN4llvm3sys2fs6removeERKNS_5TwineEb+0xc2): undefined reference to `std::system_category()'
Path.cpp:(.text._ZN4llvm3sys2fs6removeERKNS_5TwineEb+0xdd): undefined reference to `std::generic_category()'
../../lib/libLLVMSupport.a(Path.cpp.o): In function `llvm::sys::fs::access(llvm::Twine const&, llvm::sys::fs::AccessMode)':
Path.cpp:(.text._ZN4llvm3sys2fs6accessERKNS_5TwineENS1_10AccessModeE+0x5d): undefined reference to `std::generic_category()'
Path.cpp:(.text._ZN4llvm3sys2fs6accessERKNS_5TwineENS1_10AccessModeE+0xab): undefined reference to `std::system_category()'
Path.cpp:(.text._ZN4llvm3sys2fs6accessERKNS_5TwineENS1_10AccessModeE+0xee): undefined reference to `std::generic_category()'
../../lib/libLLVMSupport.a(Path.cpp.o): In function `llvm::sys::fs::status(llvm::Twine const&, llvm::sys::fs::file_status&)':
Path.cpp:(.text._ZN4llvm3sys2fs6statusERKNS_5TwineERNS1_11file_statusE+0x58): undefined reference to `std::generic_category()'
Path.cpp:(.text._ZN4llvm3sys2fs6statusERKNS_5TwineERNS1_11file_statusE+0x14c): undefined reference to `std::system_category()'
../../lib/libLLVMSupport.a(Path.cpp.o): In function `llvm::sys::fs::current_path(llvm::SmallVectorImpl<char>&)':
Path.cpp:(.text._ZN4llvm3sys2fs12current_pathERNS_15SmallVectorImplIcEE+0x18f): undefined reference to `std::system_category()'
Path.cpp:(.text._ZN4llvm3sys2fs12current_pathERNS_15SmallVectorImplIcEE+0x289): undefined reference to `std::system_category()'
Path.cpp:(.text._ZN4llvm3sys2fs12current_pathERNS_15SmallVectorImplIcEE+0x2b1): undefined reference to `std::generic_category()'
../../lib/libLLVMSupport.a(Path.cpp.o): In function `llvm::sys::fs::status(int, llvm::sys::fs::file_status&)':
Path.cpp:(.text._ZN4llvm3sys2fs6statusEiRNS1_11file_statusE+0x20): undefined reference to `std::generic_category()'
Path.cpp:(.text._ZN4llvm3sys2fs6statusEiRNS1_11file_statusE+0x119): undefined reference to `std::system_category()'
../../lib/libLLVMSupport.a(Path.cpp.o): In function `llvm::sys::fs::mapped_file_region::init(int, unsigned long, llvm::sys::fs::mapped_file_region::mapmode)':
Path.cpp:(.text._ZN4llvm3sys2fs18mapped_file_region4initEimNS2_7mapmodeE+0x34): undefined reference to `std::system_category()'
Path.cpp:(.text._ZN4llvm3sys2fs18mapped_file_region4initEimNS2_7mapmodeE+0x59): undefined reference to `std::generic_category()'
../../lib/libLLVMSupport.a(Path.cpp.o): In function `llvm::sys::fs::openFileForRead(llvm::Twine const&, int&, llvm::SmallVectorImpl<char>*)':
Path.cpp:(.text._ZN4llvm3sys2fs15openFileForReadERKNS_5TwineERiPNS_15SmallVectorImplIcEE+0x111): undefined reference to `std::system_category()'
Path.cpp:(.text._ZN4llvm3sys2fs15openFileForReadERKNS_5TwineERiPNS_15SmallVectorImplIcEE+0x149): undefined reference to `std::generic_category()'
../../lib/libLLVMSupport.a(Path.cpp.o): In function `llvm::sys::fs::openFileForWrite(llvm::Twine const&, int&, llvm::sys::fs::OpenFlags, unsigned int)':
Path.cpp:(.text._ZN4llvm3sys2fs16openFileForWriteERKNS_5TwineERiNS1_9OpenFlagsEj+0xad): undefined reference to `std::system_category()'
Path.cpp:(.text._ZN4llvm3sys2fs16openFileForWriteERKNS_5TwineERiNS1_9OpenFlagsEj+0xe9): undefined reference to `std::generic_category()'
../../lib/libLLVMSupport.a(Path.cpp.o): In function `createUniqueEntity(llvm::Twine const&, int&, llvm::SmallVectorImpl<char>&, bool, unsigned int, FSEntity)':
Path.cpp:(.text._ZL18createUniqueEntityRKN4llvm5TwineERiRNS_15SmallVectorImplIcEEbj8FSEntity+0x1a8): undefined reference to `std::generic_category()'
Path.cpp:(.text._ZL18createUniqueEntityRKN4llvm5TwineERiRNS_15SmallVectorImplIcEEbj8FSEntity+0x224): undefined reference to `std::generic_category()'
Path.cpp:(.text._ZL18createUniqueEntityRKN4llvm5TwineERiRNS_15SmallVectorImplIcEEbj8FSEntity+0x3e3): undefined reference to `std::system_category()'
../../lib/libLLVMSupport.a(Process.cpp.o): In function `llvm::sys::Process::SafelyCloseFileDescriptor(int)':
Process.cpp:(.text._ZN4llvm3sys7Process25SafelyCloseFileDescriptorEi+0x39): undefined reference to `std::generic_category()'
Process.cpp:(.text._ZN4llvm3sys7Process25SafelyCloseFileDescriptorEi+0x71): undefined reference to `std::generic_category()'
Process.cpp:(.text._ZN4llvm3sys7Process25SafelyCloseFileDescriptorEi+0xaf): undefined reference to `std::generic_category()'
../../lib/libLLVMSupport.a(Program.cpp.o): In function `llvm::sys::findProgramByName(llvm::StringRef, llvm::ArrayRef<llvm::StringRef>)':
Program.cpp:(.text._ZN4llvm3sys17findProgramByNameENS_9StringRefENS_8ArrayRefIS1_EE+0x292): undefined reference to `std::generic_category()'
../../lib/libLLVMSupport.a(Program.cpp.o): In function `llvm::sys::ChangeStdinToBinary()':
Program.cpp:(.text._ZN4llvm3sys19ChangeStdinToBinaryEv+0x5): undefined reference to `std::system_category()'
../../lib/libLLVMSupport.a(Program.cpp.o): In function `llvm::sys::ChangeStdoutToBinary()':
Program.cpp:(.text._ZN4llvm3sys20ChangeStdoutToBinaryEv+0x5): undefined reference to `std::system_category()'
collect2: error: ld returned 1 exit status
make[2]: *** [igc/IGC/llvm/build/src/bin/llvm-tblgen] Error 1
make[1]: *** [igc/IGC/llvm/build/src/utils/TableGen/CMakeFiles/llvm-tblgen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 43%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_DLL.dir/api/kv.cpp.o
[ 43%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/linux_tests_configuration.cpp.o
[ 43%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/main_linux_dll.cpp.o
[ 43%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Backend/BitProcessor.cpp.o
[ 43%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Backend/GED/Encoder.cpp.o
[ 43%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Backend/GED/GEDBitProcessor.cpp.o
[ 43%] Linking CXX shared library ../../../../../bin/libiga64.so
CMakeFiles/IGA_OLIB.dir/Frontend/LdStSyntax/MessageParsing.cpp.o: In function `std::string::_M_check(unsigned long, char const*) const':
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3326: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
CMakeFiles/IGA_OLIB.dir/Backend/GED/Decoder.cpp.o: In function `std::_Sp_counted_deleter<iga::MemManager*, std::__shared_ptr<iga::MemManager, (__gnu_cxx::_Lock_policy)2>::_Deleter<std::allocator<iga::MemManager> >, std::allocator<iga::MemManager>, (__gnu_cxx::_Lock_policy)2>::~_Sp_counted_deleter()':
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr_base.h:466: undefined reference to `operator delete(void*, unsigned long)'
CMakeFiles/IGA_OLIB.dir/Backend/GED/Decoder.cpp.o: In function `iga::DecoderBase::decodeKernel(void const*, unsigned long, bool)':
/data/compute-runtime/igc/visa/iga/IGALibrary/Backend/GED/Decoder.cpp:141: undefined reference to `operator delete(void*, unsigned long)'
CMakeFiles/IGA_OLIB.dir/Frontend/KernelParser.cpp.o: In function `iga::SyntaxError::~SyntaxError()':
/data/compute-runtime/igc/visa/iga/IGALibrary/Frontend/Parser.hpp:60: undefined reference to `operator delete(void*, unsigned long)'
CMakeFiles/IGA_OLIB.dir/Frontend/KernelParser.cpp.o: In function `iga::ParseGenKernel(iga::Model const&, char const*, iga::ErrorHandler&, iga::ParseOpts const&)':
/data/compute-runtime/igc/visa/iga/IGALibrary/Frontend/KernelParser.cpp:2977: undefined reference to `operator delete(void*, unsigned long)'
CMakeFiles/IGA_OLIB.dir/Frontend/Parser.cpp.o: In function `std::string::_M_check(unsigned long, char const*) const':
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3326: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3326: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
CMakeFiles/IGA_OLIB.dir/IR/Kernel.cpp.o: In function `iga::Kernel::~Kernel()':
/data/compute-runtime/igc/visa/iga/IGALibrary/IR/Kernel.cpp:47: undefined reference to `operator delete(void*, unsigned long)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/libiga64.so] Error 1
make[1]: *** [igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_DLL.dir/all] Error 2
[ 43%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Backend/GED/GEDUtil.cpp.o
[ 43%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Backend/GED/Interface.cpp.o
[ 44%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/drm_null_device_tests.cpp.o
[ 44%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Frontend/Floats.cpp.o
[ 44%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/mock_os_layer.cpp.o
[ 44%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Frontend/Formatter.cpp.o
[ 44%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/__/__/runtime/os_interface/debug_settings_manager.cpp.o
[ 44%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Frontend/LdStSyntax/MessageFormatting.cpp.o
[ 44%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/__/__/runtime/dll/linux/allocator_helper.cpp.o
[ 44%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/__/__/runtime/dll/linux/drm_neo_create.cpp.o
[ 44%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Frontend/LdStSyntax/Syntax.cpp.o
[ 44%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/__/__/runtime/dll/linux/options.cpp.o
[ 44%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Frontend/LdStSyntax/Tables.cpp.o
[ 44%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/IR/Block.cpp.o
[ 44%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/IR/DUAnalysis.cpp.o
[ 44%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/__/gen10/linux/dll/device_id_tests_gen10.cpp.o
[ 44%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/__/gen8/bdw/linux/dll/device_id_tests_bdw.cpp.o
[ 44%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/IR/IRChecker.cpp.o
[ 44%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/IR/ImmVal.cpp.o
[ 44%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/IR/Instruction.cpp.o
[ 44%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/__/gen9/bxt/linux/dll/device_id_tests.cpp.o
[ 44%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/__/gen9/cfl/linux/dll/device_id_tests_cfl.cpp.o
[ 45%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/IR/Kernel.cpp.o
[ 45%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/IR/Operand.cpp.o
[ 45%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/__/gen9/glk/linux/dll/device_id_tests_glk.cpp.o
[ 45%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/IR/Traversals.cpp.o
[ 45%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/IR/RegSet.cpp.o
[ 45%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/IR/Types.cpp.o
[ 45%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/MemManager/Arena.cpp.o
[ 45%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/MemManager/MemManager.cpp.o
[ 45%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Models/Models.cpp.o
[ 45%] Building CXX object igc/IGC/visa/iga/IGALibrary/CMakeFiles/IGA_ENC_LIB.dir/Timer/Timer.cpp.o
[ 45%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/__/gen9/kbl/linux/dll/device_id_tests_kbl.cpp.o
[ 45%] Building CXX object unit_tests/linux/CMakeFiles/igdrcl_linux_dll_tests.dir/__/gen9/skl/linux/dll/device_id_tests_skl.cpp.o
[ 45%] Linking CXX static library ../../../../../lib/libiga_enc64.a
[ 45%] Built target IGA_ENC_LIB
[ 45%] Linking CXX executable ../../bin/igdrcl_linux_dll_tests
../../lib/libigdrcl_lib_mockable.a(kernel.cpp.o): In function `OCLRT::Kernel::~Kernel()':
kernel.cpp:(.text+0x6d3): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(kernel.cpp.o): In function `OCLRT::Kernel::setArgSampler(unsigned int, unsigned long, void const*)':
kernel.cpp:(.text+0x29de): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(kernel.cpp.o): In function `OCLRT::Kernel::resolveArgs()':
kernel.cpp:(.text+0x3ce0): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(kernel.cpp.o): In function `OCLRT::Kernel::fillWithBuffersForAuxTranslation(std::unordered_set<OCLRT::Buffer*, std::hash<OCLRT::Buffer*>, std::equal_to<OCLRT::Buffer*>, std::allocator<OCLRT::Buffer*> >&)':
kernel.cpp:(.text+0x5bd5): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(compile.cpp.o): In function `OCLRT::Program::compile(unsigned int, _cl_device_id* const*, char const*, unsigned int, _cl_program* const*, char const**, void (*)(_cl_program*, void*), void*)':
compile.cpp:(.text+0x23a7): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(command_queue.cpp.o): In function `OCLRT::CommandQueue::obtainNewTimestampPacketNodes(unsigned long, OCLRT::TimestampPacketContainer&)':
command_queue.cpp:(.text+0x2f5f): undefined reference to `__cxa_throw_bad_array_new_length'
../../lib/libigdrcl_lib_mockable.a(context.cpp.o): In function `OCLRT::Context::createImpl(long const*, OCLRT::DeviceVector const&, void (*)(char const*, void const*, unsigned long, void*), void*, int&)':
context.cpp:(.text+0xdee): undefined reference to `__cxa_throw_bad_array_new_length'
../../lib/libigdrcl_lib_mockable.a(event.cpp.o): In function `OCLRT::TagAllocator<OCLRT::HwTimeStamps>::getTag()':
event.cpp:(.text._ZN5OCLRT12TagAllocatorINS_12HwTimeStampsEE6getTagEv[_ZN5OCLRT12TagAllocatorINS_12HwTimeStampsEE6getTagEv]+0xbc1): undefined reference to `__cxa_throw_bad_array_new_length'
../../lib/libigdrcl_lib_mockable.a(event.cpp.o): In function `OCLRT::TagAllocator<OCLRT::HwPerfCounter>::getTag()':
event.cpp:(.text._ZN5OCLRT12TagAllocatorINS_13HwPerfCounterEE6getTagEv[_ZN5OCLRT12TagAllocatorINS_13HwPerfCounterEE6getTagEv]+0xbe1): undefined reference to `__cxa_throw_bad_array_new_length'
../../lib/libigdrcl_lib_mockable.a(memory_manager.cpp.o): In function `OCLRT::MemoryManager::getEventTsAllocator()':
memory_manager.cpp:(.text+0x2a2d): undefined reference to `__cxa_throw_bad_array_new_length'
../../lib/libigdrcl_lib_mockable.a(memory_manager.cpp.o):memory_manager.cpp:(.text+0x34cd): more undefined references to `__cxa_throw_bad_array_new_length' follow
../../lib/libigdrcl_lib_mockable.a(kernel_info.cpp.o): In function `OCLRT::KernelInfo::storePatchToken(iOpenCL::SPatchKernelAttributesInfo const*)':
kernel_info.cpp:(.text+0x8d7): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(tbx_sockets_imp.cpp.o): In function `OCLRT::TbxSocketsImp::connectToServer(std::string const&, unsigned short)':
tbx_sockets_imp.cpp:(.text+0x3c3): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(gpgpu_walker_gen8.cpp.o): In function `OCLRT::HardwareInterface<OCLRT::BDWFamily>::dispatchWalker(OCLRT::CommandQueue&, OCLRT::MultiDispatchInfo const&, unsigned int, _cl_event* const*, OCLRT::KernelOperation**, OCLRT::HwTimeStamps*, OCLRT::HwPerfCounter*, OCLRT::TimestampPacketContainer*, OCLRT::TimestampPacketContainer*, OCLRT::PreemptionMode, bool, unsigned int)':
gpgpu_walker_gen8.cpp:(.text._ZN5OCLRT17HardwareInterfaceINS_9BDWFamilyEE14dispatchWalkerERNS_12CommandQueueERKNS_17MultiDispatchInfoEjPKP9_cl_eventPPNS_15KernelOperationEPNS_12HwTimeStampsEPNS_13HwPerfCounterEPNS_24TimestampPacketContainerESK_NS_14PreemptionModeEbj[_ZN5OCLRT17HardwareInterfaceINS_9BDWFamilyEE14dispatchWalkerERNS_12CommandQueueERKNS_17MultiDispatchInfoEjPKP9_cl_eventPPNS_15KernelOperationEPNS_12HwTimeStampsEPNS_13HwPerfCounterEPNS_24TimestampPacketContainerESK_NS_14PreemptionModeEbj]+0x1431): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(gpgpu_walker_gen9.cpp.o): In function `OCLRT::HardwareInterface<OCLRT::SKLFamily>::dispatchWalker(OCLRT::CommandQueue&, OCLRT::MultiDispatchInfo const&, unsigned int, _cl_event* const*, OCLRT::KernelOperation**, OCLRT::HwTimeStamps*, OCLRT::HwPerfCounter*, OCLRT::TimestampPacketContainer*, OCLRT::TimestampPacketContainer*, OCLRT::PreemptionMode, bool, unsigned int)':
gpgpu_walker_gen9.cpp:(.text._ZN5OCLRT17HardwareInterfaceINS_9SKLFamilyEE14dispatchWalkerERNS_12CommandQueueERKNS_17MultiDispatchInfoEjPKP9_cl_eventPPNS_15KernelOperationEPNS_12HwTimeStampsEPNS_13HwPerfCounterEPNS_24TimestampPacketContainerESK_NS_14PreemptionModeEbj[_ZN5OCLRT17HardwareInterfaceINS_9SKLFamilyEE14dispatchWalkerERNS_12CommandQueueERKNS_17MultiDispatchInfoEjPKP9_cl_eventPPNS_15KernelOperationEPNS_12HwTimeStampsEPNS_13HwPerfCounterEPNS_24TimestampPacketContainerESK_NS_14PreemptionModeEbj]+0x1431): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(gpgpu_walker_gen10.cpp.o): In function `OCLRT::HardwareInterface<OCLRT::CNLFamily>::dispatchWalker(OCLRT::CommandQueue&, OCLRT::MultiDispatchInfo const&, unsigned int, _cl_event* const*, OCLRT::KernelOperation**, OCLRT::HwTimeStamps*, OCLRT::HwPerfCounter*, OCLRT::TimestampPacketContainer*, OCLRT::TimestampPacketContainer*, OCLRT::PreemptionMode, bool, unsigned int)':
gpgpu_walker_gen10.cpp:(.text._ZN5OCLRT17HardwareInterfaceINS_9CNLFamilyEE14dispatchWalkerERNS_12CommandQueueERKNS_17MultiDispatchInfoEjPKP9_cl_eventPPNS_15KernelOperationEPNS_12HwTimeStampsEPNS_13HwPerfCounterEPNS_24TimestampPacketContainerESK_NS_14PreemptionModeEbj[_ZN5OCLRT17HardwareInterfaceINS_9CNLFamilyEE14dispatchWalkerERNS_12CommandQueueERKNS_17MultiDispatchInfoEjPKP9_cl_eventPPNS_15KernelOperationEPNS_12HwTimeStampsEPNS_13HwPerfCounterEPNS_24TimestampPacketContainerESK_NS_14PreemptionModeEbj]+0x1431): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(built_ins.cpp.o): In function `OCLRT::BuiltIns::getBuiltinDispatchInfoBuilder(OCLRT::EBuiltInOps, OCLRT::Context&, OCLRT::Device&)':
built_ins.cpp:(.text+0x105c): undefined reference to `std::runtime_error::runtime_error(char const*)'
../../lib/libigdrcl_lib_mockable.a(built_ins.cpp.o): In function `OCLRT::BuiltInOp<int, (OCLRT::EBuiltInOps)0>::buildDispatchInfos(OCLRT::MultiDispatchInfo&, OCLRT::BuiltinDispatchInfoBuilder::BuiltinOpParams const&) const':
built_ins.cpp:(.text._ZNK5OCLRT9BuiltInOpIiLNS_11EBuiltInOpsE0EE18buildDispatchInfosERNS_17MultiDispatchInfoERKNS_26BuiltinDispatchInfoBuilder15BuiltinOpParamsE[_ZNK5OCLRT9BuiltInOpIiLNS_11EBuiltInOpsE0EE18buildDispatchInfosERNS_17MultiDispatchInfoERKNS_26BuiltinDispatchInfoBuilder15BuiltinOpParamsE]+0xde0): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(image_transformer.cpp.o): In function `OCLRT::ImageTransformer::transformImagesTo2dArray(OCLRT::KernelInfo const&, std::vector<OCLRT::Kernel::SimpleKernelArgInfo, std::allocator<OCLRT::Kernel::SimpleKernelArgInfo> > const&, void*)':
image_transformer.cpp:(.text+0x142): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
image_transformer.cpp:(.text+0x150): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(image_transformer.cpp.o): In function `OCLRT::ImageTransformer::transformImagesTo3d(OCLRT::KernelInfo const&, std::vector<OCLRT::Kernel::SimpleKernelArgInfo, std::allocator<OCLRT::Kernel::SimpleKernelArgInfo> > const&, void*)':
image_transformer.cpp:(.text+0x2a1): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
image_transformer.cpp:(.text+0x2af): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
../../lib/libigdrcl_lib_mockable.a(build.cpp.o):build.cpp:(.text+0x14a): more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow
collect2: error: ld returned 1 exit status

**Comment by JacekDanecki** [comment]
Can you provide more details what versions (commits ID's) did you use to compile Neo. Today I've built the whole Neo stack successfully under Centos 7.5 using head's commits from all components.
