### ISSUE TITLE
Support resource sharing via EGL

### ISSUE THREAD

**Issue by krogueintel** [intel/compute-runtime#101]
Looking at runtime/api/dispatch.cpp, it appears that data sharing via EGL is not supported.

Would it be possible to add support for such images to enable more generic data sharing across API's and processes? I am looking into enabling video format conversion using OpenCL for destination formats not naively supported by the Intel Media driver (https://github.com/intel/media-driver).

Very limited support is fine where the input EGLImage are only allowed to be single-plane 1,2,3 or 4 channel formats and the OpenCL application would do the color conversion (both reads and writes) itself.

Edit:  changed to Intel Media driver as I mean to use/deal with the officially support VA driver.

**Comment by PiotrRozenfeld** [comment]
We are discussing this internally, should have conclusions in a few weeks.

**Comment by krogueintel** [comment]
If it is helpful, I can likely implement this already (by imitating the existing code in compute_runtime for VASurface and the code in Mesa/i965).

**Comment by PiotrRozenfeld** [comment]
Contributions are always welcome.
