### ISSUE TITLE
OpenCL 2.2 NEO support still planned for this year?

### ISSUE THREAD

**Issue by oscarbg** [intel/compute-runtime#110]
Hi,
I remembered that Neo site says "OpenCL 2.2 software technology support coming later in 2018"..
is still the case? as I can't see any progress just by inspecting recent commits.. altough I might be wrong..
thanks..

**Comment by PiotrRozenfeld** [comment]
Implementing OpenCL 2.2 by 2018 EOY was our intention at the time of initial NEO opensourcing. Since then, we have seen little interest from both community and customers. The asks we had received as OpenCL 2.2 were in fact requests for OpenCL C++ (which is already there with OpenCL 2.1), we plan to respond to these with expanding SPIR-V support in the near term.

**Comment by oscarbg** [comment]
yes I'm also interested mainly on OpenCL C++ ..
Thanks for informative answer..

**Comment by PiotrRozenfeld** [comment]
Hi Oscar,

Please note we recently added several new SPIR-V extensions in the driver:
•	cl_intel_spirv_subgroups
•	cl_intel_spirv_media_block_io
•	cl_intel_spirv_device_side_avc_motion_estimation

Another extension - cl_khr_spirv_no_integer_wrap_decoration - will be added soon.

We are also working with our colleagues from intel-graphics-compiler to upgrade the SPIR-V version accepted - CL_DEVICE_IL_VERSION should move beyond SPIR-V_1.0 in Q1’2019

**Comment by AdamCetnerowski** [comment]
cl_khr_spirv_no_integer_wrap_decoration - is now supported in the driver

**Comment by AdamCetnerowski** [comment]
We now officially support SPIR-V 1.2

**Comment by oscarbg** [comment]
nice!
today's release 19.16.12873 supports it already?

**Comment by AdamCetnerowski** [comment]
Not yet. This was introduced with build 12890. I expect it will be included in this week's release.

**Comment by JacekDanecki** [comment]
Closing this issue as resolved. Please reopen or create a new one if you have additional questions.

**Comment by oscarbg** [comment]
thanks!
