### ISSUE TITLE
Choice of OpenCL C++ Compiler?

### ISSUE THREAD

**Issue by pkeir** [intel/compute-runtime#118]
Is the [SPIR generator](https://github.com/KhronosGroup/SPIR) the recommended approach to compiling OpenCL C++ into SPIR-V for use with the Intel NEO compute runtime?

**Comment by PawelJurek** [comment]
Currently NEO compute runtime does not support OpenCL 2.2, therefore validation of C++ kernels is out of scope of our certification process. But if I would have to recommend a generator for C++ kernels, it would be this one. Feel free to experiment and let us know via Intel Graphics Compiler (https://github.com/intel/intel-graphics-compiler) if you encounter issues.”

**Comment by JacekDanecki** [comment]
Closing as answer was provided.
