### ISSUE TITLE
neo driver ignores CMAKE_INSTALL_SYSCONFDIR, but installs files to /etc

### ISSUE THREAD

**Issue by dvrogozh** [intel/compute-runtime#124]
I was building and installing neo driver with the following commands:
```
MY_INSTALL_DIR=/custom/install/path
cmake -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR -DCMAKE_INSTALL_SYSCONFDIR=$MY_INSTALL_DIR/etc /path/to/neo
make -j8
make install
```
Build system installed the following files (after bypassing permission error):
```
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /custom/install/path/lib64/libigdrcl.so
-- Installing: /etc/ld.so.conf.d/libintelopencl.conf
-- Installing: /etc/OpenCL/vendors/intel.icd
```
While the expectation was to have CMAKE_INSTALL_SYSCONFDIR respected, i.e.:
* $CMAKE_INSTALL_SYSCONFDIR/OpenCL/vendors/intel.icd

Secondly, I believe that build system should not have created /etc/ld.so.conf.d/libintelopencl.conf or even $CMAKE_INSTALL_PREFIX/ld.so.conf.d/libintelopencl.conf since project actually don't have any custom shared library paths which could not be matched to system paths. I believe that this file may make sense in case of project self-packaging for installation in the custom location, but I don't think this should be done within generic install path. Besides, shouldn't ocl-icd loader be able to detect the driver via $CMAKE_INSTALL_PREFIX/OpenCL/vendors/intel.icd?

The above issues would be especially important in case of cross compilation where the one will wish to preserve host system state.

**Comment by ArturHarasimiuk** [comment]
location of intel.icd is correct because it is defined in ocl-icd. folder /etc/OpenCL/vendors is scanned by ICD to find installed OpenCL drivers.

if you have a need to install in specific directory then you should use ```make install DESTDIR=<dir>``` instead of using CMAKE_INSTALL_DIR for this purpose

**Comment by JacekDanecki** [comment]
Closing as answer was provided. Feel free to reopen this issue if more information is needed.
