### ISSUE TITLE
Does the 18.1 release CPU runtime support: Pentium(R) Dual-Core  CPU E5400 @ 2.70GHz

### ISSUE THREAD

**Issue by danielsokolowski** [intel/compute-runtime#138]
The reason I ask is that the relase notes state that SSE3 is supported, but after installing the packages on Debian (followed Ubuntu install)  `clinfo` does not return any platforms. Checking with `strace` confirms the libraries are being loaded. 

The old 5.0 version (intel-opencl-r5.0 (SRB5.0) Linux driver) of the CPU runtime `clinfo` does report a platform but fails when I test some test programs, after digging it's because SSE4.1 is required (https://software.intel.com/en-us/forums/opencl/topic/506830)

**Comment by AdamCetnerowski** [comment]
Neo provides runtime for GPU-only. Other devices, including CPU, are supported in our Developer Zone: https://software.intel.com/en-us/forums/opencl

**Comment by MichalMrozek** [comment]
Looks like question is answered, closing.
