### ISSUE TITLE
Build Issue: Could not load libigdfcl.so

### ISSUE THREAD

**Issue by jebos** [intel/compute-runtime#139]
Following the descriptions found here https://gist.github.com/Brainiarc7/4f831867f8e55d35cbcb527e15f9f116 on a Ubuntu 18.10 I did:

> 
> Create the project structure:
> 
> mkdir -p ~/intel-compute-runtime/workspace
> 
> Within this workspace directory, fetch the sources for the required dependencies:
> 
> cd ~/intel-compute-runtime/workspace
> git clone -b release_70 https://github.com/llvm-mirror/llvm llvm_source
> git clone -b release_70 https://github.com/llvm-mirror/clang llvm_source/tools/clang
> git clone -b ocl-open-70 https://github.com/intel/opencl-clang llvm_source/projects/opencl-clang
> git clone -b llvm_release_70 https://github.com/KhronosGroup/SPIRV-LLVM-Translator llvm_source/projects/llvm-spirv
> git clone https://github.com/intel/llvm-patches llvm_patches
> git clone https://github.com/intel/intel-graphics-compiler igc
> git clone https://github.com/intel/compute-runtime neo
> 
> Create a build directory for the Intel Graphics Compiler under the workspace:
> 
> mkdir -p ~/intel-compute-runtime/workspace/build_igc
> 
> Then build:
> 
> cd ~/intel-compute-runtime/workspace/build_igc
> cmake ../igc/IGC
> time make -j$(nproc) VERBOSE=1

This ended up in

````
cd /home/pc/intel-compute-runtime/workspace/neo/runtime/built_ins/kernels && LD_LIBRARY_PATH=/home/pc/intel-compute-runtime/workspace/build_icr/bin /home/pc/intel-compute-runtime/workspace/build_icr/bin/ocloc -q -file aux_translation.igdrcl_built_in -device bdw -64 -out_dir /home/pc/intel-compute-runtime/workspace/build_icr/bin/built_ins/x64/gen8 -cpp_file -options -cl-kernel-arg-info
Error: Failed to load libigdfcl.so
make[2]: *** [igdrcl_lib_release/built_ins/kernels/CMakeFiles/builtins_Gen9core.dir/build.make:73: bin/built_ins/x64/gen9/aux_translation_Gen9core.spv] Error 250
`````

Any Idea whats missing / wrong?

**Comment by JacekDanecki** [comment]
Have you executed
```
sudo ldconfig
```
after installing IGC?
You can find some tips in [this issue](https://github.com/intel/compute-runtime/issues/123)

**Comment by jebos** [comment]
Well, this can be closed, Just did a clean new attempt and it worked out this time to compile, not sure what caused the issue on first run.

**Comment by eero-t** [comment]
> Well, this can be closed, Just did a clean new attempt and it worked out this time to compile, not sure what caused the issue on first run.

If you did first one build which failed, and then a second one from start, some other component probably did "ldconfig" call, which resulted IGC libraries being in dynamic linker cache.  IGC should do ldconfig on install like other libraries do (preferably so that it's allowed to fail, if install isn't done as root, as then user is supposed to have set LD_LIBRARY_PATH to point to install path instead).

**Comment by JacekDanecki** [comment]
ldconfig has been added in IGC [commit](https://github.com/intel/intel-graphics-compiler/commit/fcba69c1f9a6fd1efb7ce8a54cabe2acafe20d6a#diff-eb42e3a6a676df5441ef16072e9fb3a8). If you still observe issue with IGC installation, please fill new bug in [IGC repository](https://github.com/intel/intel-graphics-compiler/issues)
