### ISSUE TITLE
Where to download OpenCL™ Runtime 15.1 (or 14.2)?

### ISSUE THREAD

**Issue by danielsokolowski** [intel/compute-runtime#149]
Continuation to this issue: https://github.com/intel/compute-runtime/issues/138

Where can I get 'OpenCL™ Runtime 15.1' package? The official [releases](https://github.com/intel/compute-runtime/releases) only go down to 18.X, but the [release docs](https://software.intel.com/sites/default/files/managed/c9/24/opencl_runtime-15.1-release_notes.pdf) state I should be able to download for that url. 

![image](https://user-images.githubusercontent.com/273413/54875087-55d2f080-4dce-11e9-8f59-99fdf858e822.png)

**Comment by PiotrRozenfeld** [comment]
See here: https://software.intel.com/en-us/articles/legacy-opencl-drivers#latest_CPU_runtime

**Comment by PiotrRozenfeld** [comment]
Response provided - closing. 
If you have further questions for OpenCL CPU, the [forums](https://software.intel.com/en-us/forums/opencl/) might be a better place to get support.
