### ISSUE TITLE
ocloc crashes if no kernels defined

### ISSUE THREAD

**Issue by petercad** [intel/compute-runtime#153]
ocloc on Linux crashes when compiling a non-zero-length OpenCL source file with no kernels.

    echo > test.cl
    ocloc -file test.cl -device kbl

If the file is zero-length, this doesn't happen.

**Comment by MichalMrozek** [comment]
Crash is happening in IGC library.
Can you file problem there? 
https://github.com/intel/intel-graphics-compiler

**Comment by petercad** [comment]
Sure, I'll file it with IGC. Thanks!
