### ISSUE TITLE
Doesn't support Intel(R) Atom(TM) x5-Z8350 ?

### ISSUE THREAD

**Issue by zhoub** [intel/compute-runtime#154]
Hi

I'm using the Ubuntu 16.04 LTS on Up board.

Downloaded the latest release
https://github.com/intel/compute-runtime/releases/tag/19.12.12612
and installed them, **oclinfo** still returns nothing.

Is there any possible to support Atom CPU ? Thanks !

**Comment by AdamCetnerowski** [comment]
NEO support for Atom platforms starts with [Apollo Lake](https://ark.intel.com/content/www/us/en/ark/products/codename/80644/apollo-lake.html). Your CPU is older and is supported by [Beignet OpenCL GPU driver](https://github.com/intel/beignet).
