### ISSUE TITLE
source missing: unit_tests/test_files/copybuffer.elf

### ISSUE THREAD

**Issue by tjaalton** [intel/compute-runtime#157]
Hi, this file is missing source, any chance it could be built along with the rest?

**Comment by ArturHarasimiuk** [comment]
Hi,
file is here: https://github.com/intel/compute-runtime/blob/master/unit_tests/test_files/copybuffer.elf

Could you share more details on error you observe? cmake output, build log, etc...

**Comment by alalek** [comment]
Perhaps he requesting "source code" for this binary blob. I believe, source of mentioned file is `copybuffer.cl` from the same directory.

BTW, It is just a "test data" (probably some kind of reference data, if its contents are used).

**Comment by tjaalton** [comment]
Right, I'm packaging compute-runtime for Debian/Ubuntu, and I'm not sure if having this as-is is a blocker for entry or not. I know it's used only for the tests, so the worst case scenario is to not run those tests if this file has to be removed from the packaging.

**Comment by ArturHarasimiuk** [comment]
@tjaalton current content of ~canonical-x/+archive/ubuntu/x-staging looks good, intel-opencl .deb package contains all required files. You can safely skip everything what is under the unit_tests because this content is used only during the driver build.

**Comment by ArturHarasimiuk** [comment]
File removed by https://github.com/intel/compute-runtime/commit/dbe4aec7f565280f98a43370672e3a97e70dd5cb that's why I will close this issue. Feel free to open new issue if you find something new.
