### ISSUE TITLE
compute-runtime project only for 5th or newer gen processors?

### ISSUE THREAD

**Issue by maverick6664** [intel/compute-runtime#168]
I'm using i7-4790K for Fedora 30.   Until Fedora 29, beignet comes with Fedora, but it's no longer with Fedora package.  So now I'm using beignet package for Fedora 29 on Fedora 30 system.   Fortunately it works so far, but since development of beignet is no longer active, Linux OpenCL for Intel GPU is migrating to OpenCL™ Runtimes for Intel® Processors which doesn't support my processor, 4th gen core i7.

There are still many users using 4th gen or earlier processors.   So I want this project to support such processors... soon I'll no longer rely on beignet.....it's impossible to compile beignet.

Thanks.

-Tetsuji

**Comment by PiotrRozenfeld** [comment]
Michael provided an answer in a copy of this question on [Intel Software Forums](https://software.intel.com/en-us/forums/opencl/topic/809496). If you have additional questions, feel free to ask them here or there.

**Comment by 86423355844265459587182778** [comment]
Will there be support for CHT/BSW platforms (Graphics microarchitecture Gen8LP, according to [this document](https://01.org/sites/default/files/documentation/intel-gfx-bspec-osrc-chv-bsw-vol04-configurations.pdf))?

**Comment by PiotrRozenfeld** [comment]
@86423355844265459587182778 -  Cherry Trail / Braswell support is technically possible in NEO. We had no requests to provide it so far – everyone seemed to be using Beignet. Are you personally interested or just curious? If we decide to implement experimental support for Gen8LP, would you be willing to work with us on enabling and debug?

**Comment by maverick6664** [comment]
> Will there be support for CHT/BSW platforms (Graphics microarchitecture Gen8LP, according to [this document](https://01.org/sites/default/files/documentation/intel-gfx-bspec-osrc-chv-bsw-vol04-configurations.pdf))?
> 
> @maverick6664
> If you are using clang 8 and llvm 8, please try [Arch Linux's patches](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/beignet), i.e. first revert the problematic git commits as specified in the PKGBUILD, then apply [this patch](https://git.archlinux.org/svntogit/community.git/plain/trunk/llvm8.patch?h=packages/beignet).

@86423355844265459587182778 - Sorry for belated reply.   I'll try this one.   It looks like it'll work.   Thanks!

**Comment by 86423355844265459587182778** [comment]
@PiotrRozenfeld 
Yes, I would be willing to help test and debug the NEO runtime if experimental support for Gen8LP is implemented.

**Comment by gilbahat** [comment]
Hi,

I am likewise interested in making this run on my Gen8 braswell machine. Beigenet is no longer being developed and is limited to opencl 1.2. This Gen8 machine was bought not long ago, they are still on the market and can be used for productive stuff like folding@home etc.  please reopen this issue.
