### ISSUE TITLE
Can clarify which platorms will get OpenCL 2.2 support? SKL with gen9 will get it?

### ISSUE THREAD

**Issue by oscarbg** [intel/compute-runtime#17]
title says it all..
on 01.org site we see:
"with OpenCL 2.2 software technology support coming later in 2018"
just wanting to know if will only be supported on current platformls like Skylake desktop GPUs or only in upcoming Cannonlake (gen10) or even need Icelake (gen11) (know this future products and graphics gen versions from public Mesa commits)..

**Comment by AdamCetnerowski** [comment]
Any platforms supporting OpenCL 2.1 are eligible for move to OpenCL 2.2.
