### ISSUE TITLE
Conflicting declaration of ulong compiling in 32-bit mode

### ISSUE THREAD

**Issue by mkszuba** [intel/compute-runtime#179]
Compilation of Neo in 32-bit mode on amd64 fails due to conflicting declarations of ulong, as shown in the attached build log.

I guess the main question is: does Neo actually *support* 32-bit x86 platforms? I cannot see you only provide .deb packages for amd64 but I do not think I have seen any mention of 64 bits being required.

[build.log](https://github.com/intel/compute-runtime/files/3285663/build.log)

**Comment by HoppeMateusz** [comment]
Unfortunately, 32-bit NEO compilation is not supported.

**Comment by mkszuba** [comment]
Noted for possible future reference, thank you.
