### ISSUE TITLE
Support for MDAPI

### ISSUE THREAD

**Issue by TApplencourt** [intel/compute-runtime#182]
Hi,

Does the MDAPI support is currently enabled on the NEO open-source Linux driver? 

We were not able to install MDAPI (https://github.com/intel/metrics-discovery), but not able to use it using (https://github.com/intel/opencl-intercept-layer/). 

Looking at https://github.com/intel/opencl-intercept-layer/issues/70#issuecomment-481544731, it seems that NEO doesn't yet enable MDAPI.  Is this still the case?

Regards,
Thomas

**Comment by kevin-harms** [comment]
More specifically, the opencl-intercept-layer calls the interface clCreatePerfCountersCommandQueueINTEL() however in the driver, it is hard-coded to disable instrumentation.

https://github.com/intel/compute-runtime/blob/0758661c520e712c4b9be20de578ce44614481a3/runtime/os_interface/linux/hw_info_config.cpp#L148

Why is this hard-coded to false? Can we remove this line?

**Comment by PiotrRozenfeld** [comment]
We are working on opensourcing the remaining functionality, which will allow us to provide this support. 
Feel free to follow up on https://github.com/intel/metrics-discovery for details.

**Comment by JacekDanecki** [comment]
@TApplencourt Support for MDAPI was enabled in Neo in release [20.14.16441](https://github.com/intel/compute-runtime/releases/tag/20.14.16441).

**Comment by bashbaug** [comment]
I've verified that MDAPI is working with the latest drivers after adding a very small workaround to the OpenCL Intercept Layer (https://github.com/intel/opencl-intercept-layer/pull/133).  Awesome!  Thanks!

**Comment by JacekDanecki** [comment]
Closing, as it was confirmed to work.
