### ISSUE TITLE
Supports GVT-g i.e. works under this kind of virtualization..

### ISSUE THREAD

**Issue by oscarbg** [intel/compute-runtime#19]
Hi,
I think this is the last issue I have about the NEO driver:
on GVT-g setup guide (https://github.com/intel/gvt-linux/wiki/GVTg_Setup_Guide) we see:
> 6 Features Supported
> 6.1 Highlights Features
> Compute:
>     OpenCL2.0 for Windows/Linux guest
> 6.2 Validated Benchmarks
> OpenCL:
>     LuxMark, Beignet

so seems GVT-g supports Beignet OpenCL 2.0 driver.. is this new Intel Neo OpenCL tested already tested on Linux guest virtual machine using GVT-g to see if it works correctly?
hope no issues also with new GVT-g QEMU dma_buf support annonued this week: https://01.org/igvt-g/blogs/wangbo85/2018/sharing-guest-framebuffer-host

thanks..
Oscar.

**Comment by AdamCetnerowski** [comment]
This has not been validated yet. It "should just work". If you have a chance to try it, please share your experiences and file issues, if you run into any.

**Comment by MichalMrozek** [comment]
Closing this as question seems to be answered, feel free to reopen/create new issue if you encounter any problems.
