### ISSUE TITLE
Question: We need to understand future use of Neo. Will Neo be used with future discrete graphics chips? How does Neo fit with overall Intel acceleration strategies and APIs?

### ISSUE THREAD

**Issue by quanxianwang** [intel/compute-runtime#204]
the question is from REDHAT, we need answer from project owner, thanks.

**Comment by AdamCetnerowski** [comment]
NEO will be the OpenCL GPU driver for Intel on both integrated and discrete GPUs for the foreseeable future.

**Comment by MichalMrozek** [comment]
Looks like future of NEO is clarified.
If you have any more question feel free to reopen.

**Comment by quanxianwang** [comment]
Thanks All
