### ISSUE TITLE
Incorrect versions listed for wget in release 19.35.13977

### ISSUE THREAD

**Issue by bjoo** [intel/compute-runtime#208]
I just tried to install the very new 19.35.13977 driver and encountered errors when trying to wget 

```
wget https://github.com/intel/compute-runtime/releases/download/19.35.13977/intel-igc-core_1.0.10-2500_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/19.35.13977/intel-igc-opencl_1.0.10-2500_amd64.deb
```
as instructed on the release webpage. However looking at the `ww35.sum` file later on the web page I see this is because of a typo. The right versions for these 2 packages are 1.0.11 rather than 10.0.10. 

The instructions could be fixed with replacing the lines for igc-core and igc-opencl with:

```
wget https://github.com/intel/compute-runtime/releases/download/19.35.13977/intel-igc-core_1.0.11-2500_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/19.35.13977/intel-igc-opencl_1.0.11-2500_amd64.deb
```
Best wishes and thanks for the hard work on this driver.

**Comment by JacekDanecki** [comment]
Thank you for pointing at this typo, I've updated release notes.
