### ISSUE TITLE
Link with librt

### ISSUE THREAD

**Issue by isuruf** [intel/compute-runtime#216]
When building on CentOS 6, tests need to link to librt because functions like `clock_gettime` were moved to glibc in a later version than the glibc version in CentOS 6

**Comment by isuruf** [comment]
Here's an ugly patch that fixes this https://github.com/conda-forge/intel-compute-runtime-feedstock/blob/master/recipe/add_rt.diff

**Comment by AdamCetnerowski** [comment]
With CentOS 8 just released last month, CentOS 6 is not something we plan to support. External contributions are welcome. Please consider cleaning up your patch and we’ll review it.
