### ISSUE TITLE
Out-of-bounds access in shuffle() and shuffle2()

### ISSUE THREAD

**Issue by etomzak** [intel/compute-runtime#226]
OpenCL specifies that the `mask` parameter to `shuffle()` and `shuffle2()` wraps around when it is larger than the (combined) vector size(s) [[source](https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/shuffle.html)]. The compute-runtime implementation appears not to implement the wrap-around, which creates a potential out-of-bounds access.

The issue is similar to the one fixed here: https://github.com/jrprice/Oclgrind/pull/178

**Comment by JacekDanecki** [comment]
This looks like compiler bug, please open new issue in [igc repo](https://github.com/intel/intel-graphics-compiler/issues)

**Comment by paigeale** [comment]
Yes this is a bug in the compiler we will be checking in a fix for this shortly.

**Comment by paigeale** [comment]
Bug is fixed with f75a1e835cf2375e01dc6083b7988d62444aa62e. Please Close

**Comment by MichalMrozek** [comment]
Closing as @paigeale suggested.
