### ISSUE TITLE
OCL NEO driver does not support VAAPI 2.x and iHD media driver

### ISSUE THREAD

**Issue by dvrogozh** [intel/compute-runtime#24]
At the moment OCL NEO driver does not support VAAPI 2.x (thru "cl_intel_va_api_media_sharing")and, hence, iHD media driver: https://github.com/intel/media-driver. This eventually is coming from here: https://github.com/intel/compute-runtime/blob/master/runtime/os_interface/linux/options.cpp#L30.

**Comment by JacekDanecki** [comment]
Thx for reporting, I'm working on this already.
