### ISSUE TITLE
New gmmlib release 19.4.1 breaks compute-runtime stable release

### ISSUE THREAD

**Issue by chivakker** [intel/compute-runtime#246]
gmmlib-19.4.1 was released few weeks back.  There's no corresponding release from compute runtime. Please fix.

**Comment by JacekDanecki** [comment]
Starting with commit 87e948eef584c7666d4dd7ccf0b5384077deedbf Neo switched to gmmlib 19.4.1. New release will be provided when validation cycle finished. I suppose it'll be Friday 10 Jan.

**Comment by JacekDanecki** [comment]
Release [20.01.15264](https://github.com/intel/compute-runtime/releases/tag/20.01.15264) contains gmmlib 19.4.1.
