### ISSUE TITLE
OpenCL: clEnqueueUnmapMemObject hangs when called with one wait event

### ISSUE THREAD

**Issue by boxerab** [intel/compute-runtime#247]
Platform: 

Ubuntu 19
Coffee Lake
Device 0 : Intel(R) Gen9 HD Graphics NEO
Device ID is 0x55555576e7b0

runtime installed via :
`apt-get install intel-opencl-icd`

There is no issue if I use the CPU context instead.

reproducer [here](https://github.com/GrokImageCompression/latke)
Run `debayer_image`  binary.

**Comment by boxerab** [comment]
Great. When will this fix make it's way into the ubuntu intel-opencl-icd ?

**Comment by JacekDanecki** [comment]
Once validation tests passes on builds from this week, the best will be selected for new release on github next week. Together with github release I'm preparing packages on [launchpad](https://launchpad.net/~intel-opencl/+archive/ubuntu/intel-opencl).

**Comment by boxerab** [comment]
@JacekDanecki thank you !
