### ISSUE TITLE
Failed to build debug version

### ISSUE THREAD

**Issue by ruiling** [intel/compute-runtime#26]
I tried to build debug version to do some debugging. but I fail to build it. there are basically two issues.
1. EnableDxbcDump not defined but used in IGC/AdaptorCommon/customApi.cpp
2. an invalid product family was passed in to IGC::SetWorkaroundTable() which triggers an assert there.
please help to fix them.

**Comment by MichalMrozek** [comment]
According to intel/intel-graphics-compiler#9 problem is fixed.
Feel free to reopen above issue if you still see the problem.
