### ISSUE TITLE
Can't see cl_intel_subgroup_local_block_io reported on clinfo on Intel HD 530..

### ISSUE THREAD

**Issue by oscarbg** [intel/compute-runtime#262]
Hi,
don't know if cl_intel_subgroup_local_block_io it's supported on gen9 or not anyway not reported as shown in attached clinfo report using Neo 20.07:
[clinfo2.txt](https://github.com/intel/compute-runtime/files/4240540/clinfo2.txt)
EDIT: other 2 new exts cl_intel_subgroups_char cl_intel_subgroups_long are reported..

**Comment by JacekDanecki** [comment]
cl_intel_subgroup_local_block_io is supported on Gen11+, see commit: 2fb18cac9a776bc905dc0fd626386cb47be751b6

**Comment by oscarbg** [comment]
Ok.. I see.. thanks for info..
