### ISSUE TITLE
clinfo fails to recognize gpu on tiger lake 

### ISSUE THREAD

**Issue by kangshan0910** [intel/compute-runtime#274]
Hi,
I setup my tiger lake U platform with the clear linux 32580 on which the compute-runtime version is 20.01.15264-42. But "clinfo" gives none information about the gen12 gpu. It only shows a string "Number of platforms", nothing else. Does tiger lake support by compute-runtime? If supports, what compute-runtime version? I ever tried to use the latest release, but it fails to be built on clear linux.

**Comment by JacekDanecki** [comment]
Tiger Lake is supported as "early support". Can you provide more details about your setup?
Please provide output from commands:
```
uname -a
lspci -vnn
cat /proc/cmdline
lsmod
dmesg | grep -E "drm|i915"
ls -l /dev/dri/by-path/
```
and log.txt file created by command:
```
strace -f -s 255 -o log.txt clinfo
```
Can you also provide log from failing compilation on clear linux or create new issue with log?
