### ISSUE TITLE
20.13.16352 release note is wrong

### ISSUE THREAD

**Issue by yumetodo** [intel/compute-runtime#291]
https://github.com/intel/compute-runtime/releases/tag/20.13.16352

In the section of `Installation procedure on Ubuntu 18.04`, wrong version of `intel-level-zero-gpu` is shown as a step to install. As a result, 404 not found error will be shown at `wget` and dependency error will be shown at `sudo apt upgrade`.

wrong:

```
wget https://github.com/intel/compute-runtime/releases/download/20.13.16352/intel-level-zero-gpu_0.8.16259_amd64.deb
```

expected:

```
wget https://github.com/intel/compute-runtime/releases/download/20.13.16352/intel-level-zero-gpu_0.8.16352_amd64.deb
```

**Comment by JacekDanecki** [comment]
Fixed typo, thanks.
