### ISSUE TITLE
Can neo be built on Windows?

### ISSUE THREAD

**Issue by mariamrahmaani** [intel/compute-runtime#3]
I tried to build with windows cmake and seems some linux related headers is missing:
:\Neo-github\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [D:\Neo-github\build\CMakeFiles\CMakeTmp\cmTC_e39e3.vcxproj]

not sure if something missing from windows cmake environment or windows build is not in your plan.
Thanks,
Mariam

**Comment by MichalMrozek** [comment]
NEO contains Microsoft Windows support in the code base. At this time, we do not support compilation of the opensource OpenCL stack for Windows. (It is our long-term intention to offer that option.) The Windows driver can be obtained in binary form at https://downloadcenter.intel.com/product/80939/Graphics-Drivers
