### ISSUE TITLE
OpenVINO install break OpenCL environment

### ISSUE THREAD

**Issue by wdkwyf** [intel/compute-runtime#301]
Hi,
**What is wrong:**
First, I install NEO from github [release](https://github.com/intel/compute- 
    runtime/releases/tag/20.15.16524) and then run clinfo. It works well and can find my platform.
Install method: download all deb files and run
`dpkg -i *.deb`
Then, I install OpenVINO 2020.2 for Linux (not run install_NEO_OCL_driver.sh).  The OpenCL environment break. Run clinfo only show no platform.

**Solution:**
I uninstall the OpenVINO through uninstall.sh, then dpkg -i *.deb again. It works again.  So I think  OpenVINO overwrites some files.

**What I want to know:**
Does OpenVINO install process break the existing NEO environment? How can I keep my existing NEO environment during the install process?

**Comment by JacekDanecki** [comment]
Closing the issue here as it was moved to OpenVINO project.
