### ISSUE TITLE
two buffers share cacheline - one of them gets corrupted

### ISSUE THREAD

**Issue by 8tab** [intel/compute-runtime#311]
Hi, I have a scenario, when I copy the data from device to two host buffers which share a cacheline: https://gist.github.com/8tab/e510fc6fdb53c17def276887aea64e5e.
When I force the buffers' addresses to be aligned to 64 - there is no corruption.
Do I have to use cachealigned buffers or is there any issue in the runtime?

**Comment by kamdiedrich** [comment]
Hi, please check with this commit https://github.com/intel/compute-runtime/commit/080609e174b77960e62792182e0d149ae49cba4c

**Comment by 8tab** [comment]
Works for me. Thank you
