### ISSUE TITLE
Request: Cherry Trail / Braswell (Gen8LP) support

### ISSUE THREAD

**Issue by ghost** [intel/compute-runtime#317]
In https://github.com/intel/compute-runtime/issues/168#issuecomment-496568640, a developer said that Cherry Trail / Braswell support is technically possible in NEO.

Reasons for this request:
1. Braswell chips are not old (e.g. for N3160, it is in[ "Launched" status according to Intel Ark](https://ark.intel.com/content/www/us/en/ark/products/91831/intel-celeron-processor-n3160-2m-cache-up-to-2-24-ghz.html)), is Gen8LP (NEO targets Gen 8 and above), and are still useful.
2. The [beignet runtime](https://github.com/intel/beignet) is deprecated and unmaintained, not to mention that it does not support newer LLVM versions (especially LLVM 8 and above).

If support for Gen8LP is implemented, I would be happy to be a tester and report bugs that I find on my PCs with N3050 and N3160 (and probably @gilbahat as well).

**Comment by AdamCetnerowski** [comment]
We are investigating the effort required to provide basic support for platform. No ETA, but we will update this issue when more information is available.

**Comment by PiotrRozenfeld** [comment]
We concluded the engineering investigation into Cherrytrail / NEO. Unfortunately, the amount of work required for even most basic platform support is far more than anticipated given the current driver design.
