### ISSUE TITLE
oneL0: zeDriverGetProperties does not set UUID

### ISSUE THREAD

**Issue by maleadt** [intel/compute-runtime#321]
https://spec.oneapi.com/versions/latest/oneL0/core/api.html#_CPPv422ze_driver_properties_t vs https://github.com/intel/compute-runtime/blob/8ce44b0689fd8d3676ce8dffb5c97d9f92712800/level_zero/core/source/driver/driver_handle_imp.cpp#L41-L51

**Comment by jandres742** [comment]
That's correct. We are still discussing internally on what that field should be composed of.

**Comment by jandres742** [comment]
Added in a28e88369199829ae406f69766548547c53f48ce
