### ISSUE TITLE
level zero API 0.91 or 0.95?

### ISSUE THREAD

**Issue by bgoglin** [intel/compute-runtime#322]
Hello

I am porting hwloc over the level-zero API to expose the locality of the devices. I was using the L0 API documented at https://spec.oneapi.com/level-zero/latest/index.html but I failed to actually compile my code against your latest release because the sysman API differs. You seem to be using 0.91 in your binary packages (ubuntu packages) while the sysman doc is for 0.95.

Can you clarify which one is supposed to be used? If 0.95 is the latest documentation, why aren't you using/distributing it in compute-runtime releases?

Thanks

**Comment by JacekDanecki** [comment]
Closing as question was answered. Feel free to create new issue if you have questions.
