### ISSUE TITLE
255 PCI lanes when unknown

### ISSUE THREAD

**Issue by bgoglin** [intel/compute-runtime#323]
Hello

Playing with the sysman API on a laptop, I get the following PCI properties for my GPU: Gen=0 Lanes=255 maxBandwidth=0.

I am not sure why the Linux kernel doesn't report correct details for this link, but I have seen this quite often:
```
/sys/bus/pci/devices/0000:00:02.0$ cat max_link_*
Unknown speed
255
```

Anyway, sysman shouldn't return 255 here (it's likely -1 casted in u8). 0 would likely be better. Or document a special value for "unknown" for gen, lanes et bw.

Thanks

**Comment by matcabral** [comment]
Hi @bgoglin,
 
You are correct, this is a bug. 255 is the enum for PCIE_LNK_WIDTH_UNKNOWN (https://elixir.bootlin.com/linux/latest/source/include/linux/pci.h#L234). We'll add a fix to detect this, and make with be 0 in when this happens. 

Thank you for reporting this.

**Comment by matcabral** [comment]
This is already fixed: https://github.com/intel/compute-runtime/blob/master/level_zero/tools/source/sysman/pci/linux/os_pci_imp.cpp#L55

**Comment by jandres742** [comment]
Closing. @bgoglin Feel free to comment if you still see issues.
