### ISSUE TITLE
possible to use HKEY_CURRENT_USER to specify the cl_cache dir?

### ISSUE THREAD

**Issue by aisnote** [intel/compute-runtime#337]
Some app will running as medium IL on windows and can not write the key under    
 HKEY_LOCAL_MACHINE\SOFTWARE\Intel\IGFX\OCL:

**Comment by jhajducz** [comment]
I think it's enough to create 'cl_cache' directory in the same place where binary will be executed from.

**Comment by mrsabhar** [comment]
@jhajducz  What if developer wants to create in user space and dont have permission to create key?

**Comment by jhajducz** [comment]
You mean that there is no permission to create new directory ("cl_cache") in the same place where binary will be launched from? Because as far as I understand that would be all, there is no need to play with register keys then.

**Comment by aisnote** [comment]
> You mean that there is no permission to create new directory ("cl_cache") in the same place where binary will be launched from? Because as far as I understand that would be all, there is no need to play with register keys then.

yes. Lost of enterprise exe is deployed via MSI and can not write the same place.

**Comment by AdamCetnerowski** [comment]
Fix was released as part of 20.32.17625. If there are new concerns, please open a new issue.
