### ISSUE TITLE
clinfo number of platforms 0

### ISSUE THREAD

**Issue by ye-luo** [intel/compute-runtime#350]
On my laptop UHD 630 with ubuntu 20.04
Add source `https://launchpad.net/~intel-opencl/+archive/ubuntu/intel-opencl`
After installing intel-opencl-icd I got
```
$ clinfo 
Number of platforms                               0
$ ls /etc/OpenCL/vendors/
intel-cpu.icd  intel.icd
```
I'm wondering why no GPU can be found.

**Comment by jandres742** [comment]
Did you try with sudo? You might be missing being part of the video/render groups to get access to the GPU.

**Comment by ye-luo** [comment]
Adding users to the render group solves my issue. I didn't try the video group.

**Comment by MAMorgado** [comment]
Hello ye-luo. I'm having the same problem. I tried with sudo install but still I get the same problem.
Can you help me?

**Comment by JacekDanecki** [comment]
Can you provide file log.txt created by command:
```
strace -f -s 255 -o log.txt clinfo
```

**Comment by MAMorgado** [comment]
Hi Jacek,
I've opened another issue (https://github.com/intel/compute-runtime/issues/428) where I try to better explain my problem. Right now I don't get this error anymore but I get something else.
But I can recreate the problem again if you'd prefer it and post the log as you request. 
Let me know what do you think would be best.
Thank you very much,
MaM

**Comment by MAMorgado** [comment]
Either way here is my current log.txt
[log.txt](https://github.com/intel/compute-runtime/files/6753384/log.txt)

**Comment by AdamCetnerowski** [comment]
Closing this and will continue in #428

**Comment by Cherish-Gww** [comment]
> Adding users to the render group solves my issue. I didn't try the video group.

`$ usermod -aG video <user name>`
