### ISSUE TITLE
Does this repo include source code of intel-opencl supporting intel CPU?

### ISSUE THREAD

**Issue by cnjsdfcy** [intel/compute-runtime#358]
Hi,

Firstly, I installed the [Intel SDK for OpenCL](https://software.intel.com/content/www/us/en/develop/tools/opencl-sdk.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A%20IntelSoftwareNetworkBlog%20%28Intel%20Developer%20Zone%20Blog%29) on my laptop and both the CPU and GPU are detected using clinfo cmd.

Then, I uninstalled the SDK and built compute-runtime from source code (also igc and gmmlib) successfully, however the clinfo showed that only GPU device was detected.

I am wondering that the intel-opencl for CPU is not included in this compute-runtime repo, right?
Alongside support for GPU using compute-runtime, we must install the intel-opencl [debian package](https://github.com/intel/compute-runtime/releases/download/20.36.17813/intel-opencl_20.36.17813_amd64.deb) for CPU support, right?

However, as said in below release info, the intel-opencl is also included in compute-runtime repo, so I am confused.
![image](https://user-images.githubusercontent.com/5670527/93555782-9e5e7080-f9a9-11ea-8ca5-fe42bd26d2d9.png)

**Comment by JacekDanecki** [comment]
This repository provides support only for GPU. intel-opencl package in releases is for GPU only.
