### ISSUE TITLE
Vulkan compute support?

### ISSUE THREAD

**Issue by warvstar** [intel/compute-runtime#365]
With Vulkan support this could target phones without opencl, it could also target the browser through webgpu soon.

Any plans for a Vulkan backend?

**Comment by PiotrRozenfeld** [comment]
We do not expect NEO will evolve in this direction.

**Comment by kpet** [comment]
@warvstar You may want to check out [clvk](https://github.com/kpet/clvk). It's an experimental implementation of OpenCL on Vulkan that I'm maintaining.
