### ISSUE TITLE
how does  compute-runtime support docker

### ISSUE THREAD

**Issue by guoyejun** [intel/compute-runtime#366]
Happen to find that compute-runtime supports docker at https://github.com/JacekDanecki/neo-hub. 

just curious how the OpenCL driver within container works, does it communicate with OpenCL driver in host system? or does it directly talk to KMD in host system via ioctl? thanks.

**Comment by JacekDanecki** [comment]
It uses files from /dev/dri directory mapped from host, see: https://github.com/JacekDanecki/neo-hub/blob/master/test.sh#L26
So it talks to KMD in host via ioctl's.

**Comment by guoyejun** [comment]
thanks @JacekDanecki
