### ISSUE TITLE
What if exactly ocl version for intel lts 5.4.70 kernel? 

### ISSUE THREAD

**Issue by FionaZZ92** [intel/compute-runtime#367]
Could any one provide exactly ocl version matching to https://github.com/intel/linux-intel-lts/releases ?

**Comment by PiotrRozenfeld** [comment]
All of our releases this year should be compatible with 5.4-based kernel you reference, but we have not used this patched kernel in our validation.
We test our binary releases against stock kernel (whenever possible) or upstream versions. See "Quality expectations" section in our release notes.
