### ISSUE TITLE
level zero driver for DG1

### ISSUE THREAD

**Issue by wangliwei-intel** [intel/compute-runtime#370]
What is the quality level of L0 driver for DG1? Is it also pre-release?

**Comment by PiotrRozenfeld** [comment]
As indicated in the release notes, the github binary releases currently have DG1 support disabled.
This will change as soon as we will have publicly available kernel with DG1 support

**Comment by wangliwei-intel** [comment]
After I enable DG1, the compilation failed, is it supposed to be?
How can I get compilation passed? I run NEO on top of a simulator of DG1, so I do need to get DG1 involved.
Thanks.
