### ISSUE TITLE
does compute-runtime support tensorflow?

### ISSUE THREAD

**Issue by guoyejun** [intel/compute-runtime#372]
There's a path to provide computing capability for tensorflow with opencl:  tensorflow -> eigen -> SYCL -> OpenCL. Is compute-runtime workable for this path? thanks.

**Comment by jandres742** [comment]
@guoyejun SYCL already supports OpenCL and Level Zero, see here https://github.com/intel/llvm/tree/sycl/sycl/plugins/, so path mentioned is possible if you have TF and Eigen implementation on top of SYCL.

**Comment by BartusW** [comment]
@guoyejun, you can toggle between these two GPU backend api: Level-0 or OpenCL which is called by SYCL RT:
export SYCL_BE=PI_OPENCL 
or
export SYCL_BE=PI_LEVEL0

**Comment by AdamCetnerowski** [comment]
Closing as this has been answered
