### ISSUE TITLE
Add P010 support in D3D interop

### ISSUE THREAD

**Issue by rcombs** [intel/compute-runtime#380]
This was added to the VAAPI interop in 4733e51770e76341ecb6006fe6ab5e7b61735341, but is still missing from the D3D code, preventing interop with HDR video. Can this be added? The D3D code seems largely analogous.

**Comment by HoppeMateusz** [comment]
P010 format  should be available in cl_khr_d3d10_sharing and cl_khr_d3d11_sharing.

**Comment by AdamCetnerowski** [comment]
Closing as an answer was provided.
