### ISSUE TITLE
uninstall instructions

### ISSUE THREAD

**Issue by jeyblu** [intel/compute-runtime#381]
We've installed the compute runtime on an Ubuntu system using the instructions and binaries from https://github.com/intel/compute-runtime/releases

As new releases become available, we want to update the runtime on the system. Can you provide the instructions to uninstall the runtime from the system before we install the new release? Thanks.

**Comment by JacekDanecki** [comment]
To uninstall packages you can use command:
```
dpkg -P intel-gmmlib intel-igc-opencl intel-ocloc intel-igc-core intel-level-zero-gpu intel-opencl
```

**Comment by AdamCetnerowski** [comment]
Closing as this has been answered
