### ISSUE TITLE
Enable P010 support in VAAPI interop by default

### ISSUE THREAD

**Issue by rcombs** [intel/compute-runtime#382]
This functionality seems to be working fine in my testing; any particular reason for it to still be behind a flag?

**Comment by kamdiedrich** [comment]
Please try with latest driver

**Comment by mooninite** [comment]
Here is the commit: https://github.com/intel/compute-runtime/commit/17051459eacc2979e039ca6669b4c247b6d75fb1

There is no released driver yet so you will need to compile from a snapshot.

Thank you for working on this.

**Comment by AdamCetnerowski** [comment]
Change was released in [20.51.18762](https://github.com/intel/compute-runtime/releases/tag/20.51.18762)
