### ISSUE TITLE
Help: file failed to open for reading /WDKVersion.txt

### ISSUE THREAD

**Issue by samgo1** [intel/compute-runtime#383]
I downloaded the master branch and when I try to cmake into the directory, i get `CMake Error at CMakeLists.txt:318 (file):
  file failed to open for reading (No such file or directory):

    /WDKVersion.txt`
I just installed the Windows Driver Kit for Windows 10 SDK (10.0.19041.1). I would appreciate some help on where can I get this WDKVersion.txt file? Thank you

**Comment by AdamCetnerowski** [comment]
At this time, we do not support compilation of the stack for Windows.

**Comment by samgo1** [comment]
thanks for your reply @AdamCetnerowski
