### ISSUE TITLE
Dpkg: error while install

### ISSUE THREAD

**Issue by adrastee** [intel/compute-runtime#388]
Hi,
I have downloaded the six deb package following install notes at https://github.com/intel/compute-runtime/releases
 and then :
```
$ sudo dpkg -i *.deb
(...)
dpkg: dependency problems prevent configuration of intel-opencl:
 intel-opencl-icd (20.44.18297-1) breaks intel-opencl and is installed.

dpkg: error processing package intel-opencl (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 intel-opencl

```

So I did:
`$ sudo apt remove  intel-opencl`
and again `sudo dpkg -i *.deb`, same issue.

Any help appreciated, thanks!

**Comment by JablonskiMateusz** [comment]
@adrastee  could you retry after uninstalling `intel-opencl-icd` package?

**Comment by adrastee** [comment]
It works! Thanks.
