### ISSUE TITLE
Does OpenCL runtime supports Mesa Intel® UHD Graphics (CML GT2) device?

### ISSUE THREAD

**Issue by ywu** [intel/compute-runtime#401]
As title

**Comment by PiotrRozenfeld** [comment]
This is already covered in our FAQ: 
https://github.com/intel/compute-runtime/blob/master/FAQ.md#how-can-i-check-that-my-specific-device-is-supported-by-the-driver

Let us know if this works for you.

**Comment by ywu** [comment]
Yes. Thanks so much! Didn't see that. Apologies for my stupid question.

**Comment by AdamCetnerowski** [comment]
Closing as answered. Please open a new issue, if you have more questions.
