### ISSUE TITLE
Application aborted when using the VA Media Sharing extensions

### ISSUE THREAD

**Issue by george-norton** [intel/compute-runtime#410]
Hello,

We recently upgraded from compute-runtime 20.26.17199 to 21.07.19042 and we are seeing some strange behaviour when using the VA Media Sharing Extensions. Typically our application aborts with:

    Abort was called at 35 line in file:
    intel-compute-runtime/shared/source/memory_manager/multi_graphics_allocation.cpp

But we have also seen what look like random file descriptors in other parts of our application apparently spontaneously closing. It looks a lot like something in the compute-runtime is calling `close` twice. I have bisected the changes and it appears the failures began with:
    b4444c766047ef961eabecb4edd79c6ef4cd9674: Close fd after each drm ioctl prime fd to handle

This change was also tweaked and refactored in:
    4ca17847124b2f8862b1ee46c65f77af702759b4: Fixed close fd after calling drm ioctl prime fd to handle
    b4444c766047ef961eabecb4edd79c6ef4cd9674: Move close shared handle to the upper layer on Linux

I added some tracing to `VASurface::createSharedVaSurface` and I see that occasionally `sharedHandle` seems to just get closed midway through the function call. When this happens before the call to `createGraphicsAllocationFromSharedHandle`, `alloc` is returned as `nullptr` and `multiGraphicsAllocation.addAllocation(alloc);` panics. I don't really understand much about what is going wrong here. Having revered the 3 commits above our application appears to be running well, but presumably there may be some resource leak?

**Comment by george-norton** [comment]
A little more about our application. I am running on CentOS 7 (3.10.0-957.21.3.el7.x86_64) on a gen9 GPU (E3-1578L v5). I am running the following Intel media packages:
* intel-compute-runtime 21.07.19042
* intel-igc 1.0.6087
* intel-gmmlib 20.4.1
* intel-media-driver 21.1.1
* intel-mediasdk 21.1.1
* libva 2.10.0
* level-zero 1.1.0

Our application is heavily multi-threaded, the compute-runtime is used to read logo data into MediaSDK buffers for composition - the output buffers are NV12. We are calling:

1. `clCreateFromVA_APIMediaSurfaceINTEL` on both the Y and UV planes.
2. `clEnqueueAcquireVA_APIMediaSurfacesINTEL` to acquire both surfaces
3. OpenCL code to load the data from various different formats
4. `clEnqueueReleaseVA_APIMediaSurfacesINTEL`
5. `clReleaseMemObject` on both the Y and UV planes.

We have multiple instances of this code running concurrently on different OpenCL queues. The code is a little inefficient, steps 1 and 5 could be done once at the time of surface allocation.

**Comment by AdamCetnerowski** [comment]
We are working on a fix. We will update the issue once it's available.

**Comment by smilczar** [comment]
Fixed in ci-neo-19380.
[e2408de](https://github.com/intel-innersource/drivers.gpu.compute.runtime/commit/e2408de11ae820e009bd81e29441eece16aa7b06) Ensure shared handle be closed once on Linux

**Comment by AdamCetnerowski** [comment]
Closing as this is resolved.
