### ISSUE TITLE
New or incorrect file in ww19.sum?

### ISSUE THREAD

**Issue by cxhamilton** [intel/compute-runtime#423]
I am getting an error when following the install/update instructions for release 21.19.19792.

```
$ wget https://github.com/intel/compute-runtime/releases/download/21.19.19792/ww19.sum
$ sha256sum -c ww19.sum 
sha256sum: buildy: No such file or directory
buildy: FAILED open or read
intel-gmmlib_21.1.2_amd64.deb: OK
intel-igc-core_1.0.7181_amd64.deb: OK
intel-igc-opencl_1.0.7181_amd64.deb: OK
intel-level-zero-gpu_1.1.19792_amd64.deb: OK
intel-ocloc_21.19.19792_amd64.deb: OK
intel-opencl_21.19.19792_amd64.deb: OK
sha256sum: WARNING: 1 listed file could not be read
```

This is the offending file listed in ww19.sum:

`94917c57c70d3bbbbfab62bb45c27398de590ef6dae34d84b78d8db203a1e84d  buildy
`

Is there a missing package that is a part of this release that satisfies this dependency or was the file incorrectly added to the checksum file?

**Comment by JacekDanecki** [comment]
It was incorrectly added to checksum file. Corrected now.
