### ISSUE TITLE
how does a kernel map to hardware SIMD thread

### ISSUE THREAD

**Issue by guoyejun** [intel/compute-runtime#426]
As far as I know, one OpenCL kernel instance is a work-item, and one OpenCL kernel instance is mapped to one lane of the SIMD-n.

So, if the OpenCL kernel is compiled with SIMD-16, 16 kernel instances (16 work items) are mapped to one hardware SIMD thread. Is this right? thanks.

**Comment by alalek** [comment]
BTW, there are some materials which may clarify questions:
- https://software.intel.com/en-us/articles/introduction-to-gen-assembly
- https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-bdw-vol07-3d_media_gpgpu_3.pdf
