### ISSUE TITLE
DEB packages with DG1 support

### ISSUE THREAD

**Issue by al42and** [intel/compute-runtime#427]
Hello!

For now, the DEB packages for weekly compute-runtime releases are compiled without DG1 support, as stated in the release notes.

Are there any plans to make binary releases with DG1 support, not requiring users to manually compile from sources?

**Comment by PiotrRozenfeld** [comment]
Please see https://dgpu-docs.intel.com/installation-guides/ubuntu/index.html - packages available at repositories.intel.com have DG1 support enabled.

**Comment by AdamCetnerowski** [comment]
Closing as answer was provided.
