### ISSUE TITLE
Open CL on Comet Lake UHD Graphics

### ISSUE THREAD

**Issue by MAMorgado** [intel/compute-runtime#428]
Hello,
Does your program work for Comet Lake UHD Graphics? I noticed that it's not on the supported platforms... 
I need OpenCL version 3.0 if possible.
I tried to install (sudo apt-get install intel-opencl-icd) but when I run clinfo I only get 
Number of platforms                               0

If I follow the instructions in Installation procedure on Ubuntu 18.04/20.04 ( i'm using ubuntu 20.04) during the last step I have the following error:

(Reading database ... 323160 files and directories currently installed.)
Preparing to unpack intel-gmmlib_21.1.3_amd64.deb ...
Unpacking intel-gmmlib (21.1.3) over (21.1.3) ...
dpkg: warning: downgrading intel-igc-core from 1.0.7712 to 1.0.7683
Preparing to unpack intel-igc-core_1.0.7683_amd64.deb ...
Unpacking intel-igc-core (1.0.7683) over (1.0.7712) ...
dpkg: warning: downgrading intel-igc-opencl from 1.0.7712 to 1.0.7683
Preparing to unpack intel-igc-opencl_1.0.7683_amd64.deb ...
Unpacking intel-igc-opencl (1.0.7683) over (1.0.7712) ...
dpkg: warning: downgrading intel-level-zero-gpu from 1.1.20114 to 1.1.20098
Preparing to unpack intel-level-zero-gpu_1.1.20098_amd64.deb ...
Unpacking intel-level-zero-gpu (1.1.20098) over (1.1.20114) ...
dpkg: warning: downgrading intel-ocloc from 21.25.20114 to 21.24.20098
Preparing to unpack intel-ocloc_21.24.20098_amd64.deb ...
Unpacking intel-ocloc (21.24.20098) over (21.25.20114) ...
Selecting previously unselected package intel-opencl.
Preparing to unpack intel-opencl_21.24.20098_amd64.deb ...
Unpacking intel-opencl (21.24.20098) ...
Replaced by files in installed package intel-opencl-icd (21.23.20043+i571~u20.04) ...
Setting up intel-gmmlib (21.1.3) ...
Setting up intel-igc-core (1.0.7683) ...
Setting up intel-igc-opencl (1.0.7683) ...
Setting up intel-level-zero-gpu (1.1.20098) ...
Setting up intel-ocloc (21.24.20098) ...
dpkg: dependency problems prevent configuration of intel-opencl:
 intel-opencl-icd (21.23.20043+i571~u20.04) breaks intel-opencl and is installed.

dpkg: error processing package intel-opencl (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Errors were encountered while processing:
 intel-opencl
sudo apt-get install intel-opencl-icd

And finally if I remove intel-opencl (sudo apt-get remove intel-opencl-icd) and I re-do the last instruction of the installation procedure for ubuntu It installs without problem and I get the following clinfo with Null Platform problems.

Number of platforms                               1
  Platform Name                                   Intel(R) OpenCL HD Graphics
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 3.0 
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_intel_command_queue_families cl_intel_subgroups cl_intel_required_subgroup_size cl_intel_subgroups_short cl_khr_spir cl_intel_accelerator cl_intel_driver_diagnostics cl_khr_priority_hints cl_khr_throttle_hints cl_khr_create_command_queue cl_intel_subgroups_char cl_intel_subgroups_long cl_khr_il_program cl_intel_mem_force_host_memory cl_khr_subgroup_extended_types cl_khr_subgroup_non_uniform_vote cl_khr_subgroup_ballot cl_khr_subgroup_non_uniform_arithmetic cl_khr_subgroup_shuffle cl_khr_subgroup_shuffle_relative cl_khr_subgroup_clustered_reduce cl_intel_device_attribute_query cl_khr_fp64 cl_khr_subgroups cl_intel_spirv_device_side_avc_motion_estimation cl_intel_spirv_media_block_io cl_intel_spirv_subgroups cl_khr_spirv_no_integer_wrap_decoration cl_intel_unified_shared_memory_preview cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_intel_planar_yuv cl_intel_packed_yuv cl_intel_motion_estimation cl_intel_device_side_avc_motion_estimation cl_intel_advanced_motion_estimation cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_3d_image_writes cl_intel_media_block_io cl_intel_va_api_media_sharing cl_intel_sharing_format_query cl_khr_pci_bus_info 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             INTEL

  Platform Name                                   Intel(R) OpenCL HD Graphics
Number of devices                                 1
  Device Name                                     Intel(R) UHD Graphics [0x9bca]
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 3.0 NEO 
  Driver Version                                  21.24.20098
  Device OpenCL C Version                         OpenCL C 3.0 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               24
  Max clock frequency                             1150MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              32
  Max sub-groups per work group                   32
  Sub-group sizes (Intel)                         8, 16, 32
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 1 / 1       
    half                                                 8 / 8        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              13188349952 (12.28GiB)
  Error Correction support                        No
  Max memory allocation                           4294959104 (4GiB)
  Unified memory for Host and Device              Yes
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   No
    Fine-grained system sharing                   No
    Atomics                                       No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics                 
    SVM                                           64 bytes
    Global                                        64 bytes
    Local                                         64 bytes
  Max size for global variable                    65536 (64KiB)
  Preferred total size of global vars             4294959104 (4GiB)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        524288 (512KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            268434944 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   4 bytes
    Pitch alignment for 2D image buffers          4 pixels
    Max 2D image size                             16384x16384 pixels
    Max planar YUV image size                     16384x16352 pixels
    Max 3D image size                             16384x16384x2048 pixels
    Max number of read image args                 128
    Max number of write image args                128
    Max number of read/write image args           128
  Max number of pipe args                         16
  Max active pipe reservations                    1
  Max pipe packet size                            1024
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Max number of constant args                     8
  Max constant buffer size                        4294959104 (4GiB)
  Max size of kernel argument                     2048 (2KiB)
  Queue properties (on host)                      
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Queue properties (on device)                    
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                131072 (128KiB)
    Max size                                      67108864 (64MiB)
  Max queues on device                            1
  Max events on device                            1024
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      83ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Sub-group independent forward progress        Yes
    IL version                                    SPIR-V_1.2 
    SPIR versions                                 1.2 
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                block_motion_estimate_intel;block_advanced_motion_estimate_check_intel;block_advanced_motion_estimate_bidirectional_check_intel;
  Motion Estimation accelerator version (Intel)   2
    Device-side AVC Motion Estimation version     1
      Supports texture sampler use                Yes
      Supports preemption                         No
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_intel_command_queue_families cl_intel_subgroups cl_intel_required_subgroup_size cl_intel_subgroups_short cl_khr_spir cl_intel_accelerator cl_intel_driver_diagnostics cl_khr_priority_hints cl_khr_throttle_hints cl_khr_create_command_queue cl_intel_subgroups_char cl_intel_subgroups_long cl_khr_il_program cl_intel_mem_force_host_memory cl_khr_subgroup_extended_types cl_khr_subgroup_non_uniform_vote cl_khr_subgroup_ballot cl_khr_subgroup_non_uniform_arithmetic cl_khr_subgroup_shuffle cl_khr_subgroup_shuffle_relative cl_khr_subgroup_clustered_reduce cl_intel_device_attribute_query cl_khr_fp64 cl_khr_subgroups cl_intel_spirv_device_side_avc_motion_estimation cl_intel_spirv_media_block_io cl_intel_spirv_subgroups cl_khr_spirv_no_integer_wrap_decoration cl_intel_unified_shared_memory_preview cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_intel_planar_yuv cl_intel_packed_yuv cl_intel_motion_estimation cl_intel_device_side_avc_motion_estimation cl_intel_advanced_motion_estimation cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_3d_image_writes cl_intel_media_block_io cl_intel_va_api_media_sharing cl_intel_sharing_format_query cl_khr_pci_bus_info 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [INTEL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform
	NOTE:	your OpenCL library only supports OpenCL 2.1,
		but some installed platforms support OpenCL 3.0.
		Programs using 3.0 features may crash
		or behave unexpectedly

Can you provide some help?

**Comment by MAMorgado** [comment]
Update: If I follow the instructions in Installation procedure on Ubuntu 18.04/20.04 ( i'm using ubuntu 20.04) during the last step I have the following error:
(Reading database ... 323160 files and directories currently installed.)
Preparing to unpack intel-gmmlib_21.1.3_amd64.deb ...
Unpacking intel-gmmlib (21.1.3) over (21.1.3) ...
dpkg: warning: downgrading intel-igc-core from 1.0.7712 to 1.0.7683
Preparing to unpack intel-igc-core_1.0.7683_amd64.deb ...
Unpacking intel-igc-core (1.0.7683) over (1.0.7712) ...
dpkg: warning: downgrading intel-igc-opencl from 1.0.7712 to 1.0.7683
Preparing to unpack intel-igc-opencl_1.0.7683_amd64.deb ...
Unpacking intel-igc-opencl (1.0.7683) over (1.0.7712) ...
dpkg: warning: downgrading intel-level-zero-gpu from 1.1.20114 to 1.1.20098
Preparing to unpack intel-level-zero-gpu_1.1.20098_amd64.deb ...
Unpacking intel-level-zero-gpu (1.1.20098) over (1.1.20114) ...
dpkg: warning: downgrading intel-ocloc from 21.25.20114 to 21.24.20098
Preparing to unpack intel-ocloc_21.24.20098_amd64.deb ...
Unpacking intel-ocloc (21.24.20098) over (21.25.20114) ...
Selecting previously unselected package intel-opencl.
Preparing to unpack intel-opencl_21.24.20098_amd64.deb ...
Unpacking intel-opencl (21.24.20098) ...
Replaced by files in installed package intel-opencl-icd (21.23.20043+i571~u20.04) ...
Setting up intel-gmmlib (21.1.3) ...
Setting up intel-igc-core (1.0.7683) ...
Setting up intel-igc-opencl (1.0.7683) ...
Setting up intel-level-zero-gpu (1.1.20098) ...
Setting up intel-ocloc (21.24.20098) ...
dpkg: dependency problems prevent configuration of intel-opencl:
 intel-opencl-icd (21.23.20043+i571~u20.04) breaks intel-opencl and is installed.

dpkg: error processing package intel-opencl (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Errors were encountered while processing:
 intel-opencl

**Comment by MAMorgado** [comment]
Any news :(?

**Comment by JacekDanecki** [comment]
Comet Lake is  supported, see: https://github.com/intel/compute-runtime/blob/master/shared/source/dll/devices/devices_base.inl#L169.
You can't mix packages from different sources. If you want to use packages from github release, you have to remove previously installed packages.
Can you upgrade ocl-icd package to fix problems with NULL platform?

**Comment by MAMorgado** [comment]
Hi Jacek. Thank you for your reply. 
I did what you asked and it seems to have solved the problem with the null no platform detection. Thank you very much. This is what I get back now:

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel(R) OpenCL HD Graphics
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [INTEL]
  clCreateContext(NULL, ...) [default]            Success [INTEL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Intel(R) OpenCL HD Graphics
    Device Name                                   Intel(R) UHD Graphics [0x9bca]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Intel(R) OpenCL HD Graphics
    Device Name                                   Intel(R) UHD Graphics [0x9bca]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Intel(R) OpenCL HD Graphics
    Device Name                                   Intel(R) UHD Graphics [0x9bca]

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1
	NOTE:	your OpenCL library only supports OpenCL 2.1,
		but some installed platforms support OpenCL 3.0.
		Programs using 3.0 features may crash
		or behave unexpectedly
The only thing that might be wrong is the 3.0 vs 2.1 note in the end, but i don't know if it's normal...

**Comment by JacekDanecki** [comment]
You need to install ocl-icd 2.2.13 with OpenCL 3.0 support, see: https://github.com/OCL-dev/ocl-icd/commit/3b7ded60ebb7e1afddcbae6f82ac8645b276e358#diff-7ee66c4f1536ac84dc5bbff1b8312e2eef24b974b3e48a5c5c2bcfdf2eb8f3ceR6

**Comment by Kerilk** [comment]
I create a ppa for this purpose:
https://launchpad.net/~ocl-icd/+archive/ubuntu/ppa
It should allow for installing the latest ocl-icd on recent  (and not so recent) ubuntus.

Please also note that the clinfo here is outdated as well so you may get a slightly different warning once the loader is updated (see https://github.com/Oblomov/clinfo/pull/55).

**Comment by JacekDanecki** [comment]
Closing issue, please create new issue when you find any problems.
