### ISSUE TITLE
Support for SPIR-V Specialization Constants

### ISSUE THREAD

**Issue by tremmelg** [intel/compute-runtime#44]
Is there an estimate of when the Compute Runtime will support [SPIR-V specialization constants](https://www.khronos.org/registry/spir-v/specs/1.2/SPIRV.html#_a_id_specializationsection_a_specialization) and the corresponding [OpenCL 2.2 API](https://www.khronos.org/registry/OpenCL/specs/opencl-2.2.html#_setting_spir_v_specialization_constants)? Perhaps as an extension before OpenCL 2.2 support itself is released?

I would be interested in prototyping [SYCL specialization constants](https://github.com/codeplaysoftware/standards-proposals/blob/master/spec-constant/index.md) and evaluating their effect on runtime performance, code size and compilation time on Intel hardware.

**Comment by PiotrRozenfeld** [comment]
We are exploring how to fit this into our current schedule. OpenCL 2.2 effort will start no sooner than in Q3. Once it begins, you will be able to see our progress as development will be done on master branch.

**Comment by kmazurki** [comment]
We have a preliminary plan to implement spec constants in IGC till the end of Q4, This plan might be however a subject to change based on the progress in external dependencies.

**Comment by PiotrRozenfeld** [comment]
This is still in our plans - IGC support should be available in Q1'19.

**Comment by AdamCetnerowski** [comment]
IGC support has been added. Runtime piece will be provided in Q2'19

**Comment by jchodor** [comment]
RT implementation is ready -  971eb7a1b4598491470216f26ede0cc8cf3e7993

**Comment by jchodor** [comment]
Additional RT changes : https://github.com/intel/compute-runtime/commit/5cde27ed0309aa421722db77f8b42b54b02a67df

**Comment by jchodor** [comment]
Let us know in case of problems with this feature.
