### ISSUE TITLE
cpu too high

### ISSUE THREAD

**Issue by pobin6** [intel/compute-runtime#449]
in th file: ./shared/source/command_stream/command_stream_receiver.cpp
```C++
    while (*getTagAddress() < taskCountToWait && timeDiff <= timeoutMicroseconds) {
        std::this_thread::yield();
        CpuIntrinsics::pause();

        if (enableTimeout) {
            time2 = std::chrono::high_resolution_clock::now();
            timeDiff = std::chrono::duration_cast<std::chrono::microseconds>(time2 - time1).count();
        }
    }
```
it waste a lot of cpu time in waiting result, can not use callback or interrupt?

**Comment by BartoszDunajski** [comment]
This function should fallback into callback/interrupt mode after timeout (depending on platform).
To enable that mode by default, you can create your command queue with CL_QUEUE_THROTTLE_LOW_KHR or use PowerSavingMode=1 debug variable.

**Comment by JacekDanecki** [comment]
Closing issue, as it's “expected behavior.
