### ISSUE TITLE
Wrong API version in latest release notes

### ISSUE THREAD

**Issue by maleadt** [intel/compute-runtime#464]
Building compute-runtime 21.41.21220 against oneAPI API 1.2.13, as linked in the release notes, doesn't work due to missing definitions of e.g. `zet_metric_group_exp_dditable_t`. I assume this needs to be 1.2.43, the API implemented by loader 1.5.

**Comment by maleadt** [comment]
Right, but the `Compatible with API 1.2` linking to the documentation of 1.2.13 seems to imply that older loaders that implement previous versions of the API would work too. It should probably more strict in mentioning it requires API 1.2.43?

**Comment by jandres742** [comment]
link has been corrected. Please see https://github.com/intel/compute-runtime/releases/tag/21.43.21438 for instance.
@maleadt  please confirm.

**Comment by maleadt** [comment]
Doesn't look like that in the latest release? https://github.com/intel/compute-runtime/releases/tag/21.44.21506

**Comment by jandres742** [comment]
@maleadt  could you elaborate? we have this in the release notes for that release

oneapi-src/level-zero@v1.5.4 (Compatible with oneAPI Level Zero API Spec v1.2), and from there, you see the link opens to https://spec.oneapi.io/level-zero/1.2.43/index.html.

**Comment by maleadt** [comment]
Ah yes, I guess I expected 1.2.43 to be mentioned and not just there in the link (i.e. as it was done in https://github.com/intel/compute-runtime/releases/tag/21.43.21438).

But that's fine for me.

**Comment by AdamCetnerowski** [comment]
Closing as this is resolved.
