### ISSUE TITLE
Latest version nr doesn't match

### ISSUE THREAD

**Issue by poneli** [intel/compute-runtime#468]
Hi,

When trying to install 21.42.21270 the deb's are wrongly named with a 0 added before:
intel-level-zero-gpu_1.2.021270_amd64.deb
intel-opencl-icd_21.42.021270_amd64.deb

Also when checking installed version it's printed out with the wrongly added 0 before:
dpkg -s intel-opencl-icd | awk '/^Version:/ { print $NF }'
21.42.021270

**Comment by poneli** [comment]
Why is the zero added again in release 21.43.21438?
/download/21.43.21438/intel-opencl-icd_21.43.021438_amd64.deb
/download/21.43.21438/intel-level-zero-gpu_1.2.021438_amd64.deb

**Comment by JacekDanecki** [comment]
@poneli it was fixed in https://github.com/intel/compute-runtime/commit/5869948389ec1ff1404d6d9459820899e0e4ffdc

**Comment by AdamCetnerowski** [comment]
Closing as resolved
