### ISSUE TITLE
OpenCL broken in WSL2 on Dell Inspiron 7506 2-in-1 laptop

### ISSUE THREAD

**Issue by mattcurfman** [intel/compute-runtime#469]
**System:**
Dell Inspiron 7506 2-in-1 laptop, with Intel(r) Iris(r) Xe Graphics (TGL) and Intel(r) Iris(r) Xe MAX Graphics (DG1)
Windows 11, display driver 30.0.100.9955 (Windows)
WSL2 Ubuntu 20.04, OpenCL driver 21.37.20939

In a WSL2 Ubuntu command box:
```
$ clinfo
Abort was called at 35 line in file:
/opt/src/opencl/shared/source/os_interface/windows/os_context_win.cpp
Aborted
```

If I then disable the Intel(r) Iris(r) XE MAX Graphics device in the Windows control panel, then OpenCL works in WSL2 (but only for Integrated Graphics)

**Note**: This is one of those laptops that has both an integrated graphics GPU and a discrete graphics GPU.

**Comment by jchodor** [comment]
This crash should be fixed with latest release (https://github.com/intel/compute-runtime/releases/tag/21.44.21506). However, our initial focus was on enabling integrated graphics for WSL2. Discrete support, including Iris(r) Xe MAX Graphics (DG1), is work in progress.

**Comment by AdamCetnerowski** [comment]
Fix provided. Please re-open or open a new issues if still reoccurs.

**Comment by mattcurfman** [comment]
Confirmed fixed, thanks!
