### ISSUE TITLE
Should add description for intel-gmmlib-devel packet into item 2 (Download all *.deb packages) for 21.44 release

### ISSUE THREAD

**Issue by lznamens** [intel/compute-runtime#474]
wget https://github.com/intel/compute-runtime/releases/download/21.44.21506/intel-gmmlib-devel_21.2.1_amd64.deb

Currently it's absent.

**Comment by JacekDanecki** [comment]
It's optional package, required only if you want to build Neo yourself.
sha256 sums were corrected in release notes, and ww44.sum file was updated.

**Comment by lznamens** [comment]
Thanks!
