### ISSUE TITLE
Can anyone help me install opencl library on wsl?

### ISSUE THREAD

**Issue by Airbala** [intel/compute-runtime#476]
I have an intel gpu UHD Graphics. My host OS is win11. I want to let my wsl2 on windows support opencl for my UHD Graphic, and I don't know what to do after I follow the instruction on Github and failed. Can Anyone HELP ME PLZ?

**Comment by JablonskiMateusz** [comment]
Hi @Airbala, 
could you describe what steps did you take and what issue are you facing now?

**Comment by JablonskiMateusz** [comment]
@Airbala ping

**Comment by Airbala** [comment]
Thank for your kind reply.The OpenCL library works well on my wsl. I just install an intel library. It't very wired. It just worked and I don't know why.

**Comment by JablonskiMateusz** [comment]
Cool. I'm closing this issue as you mentioned that issue is resolved.
