### ISSUE TITLE
Has the latest OpenCL release (21.46.21636) supported Adler Lake? Thanks!

### ISSUE THREAD

**Issue by heyu1** [intel/compute-runtime#479]

**Comment by JablonskiMateusz** [comment]
Hi @heyu1. Could you specify which Alder Lake platform?

**Comment by heyu1** [comment]
ADL-S and ADL-P

**Comment by JablonskiMateusz** [comment]
I hope they should be supported. You can check list of supported device ids here:
https://github.com/intel/compute-runtime/blob/21.46.21636/shared/source/dll/devices/devices_additional.inl#L10 and here https://github.com/intel/compute-runtime/blob/21.46.21636/shared/source/dll/devices/devices_base.inl#L35

**Comment by heyu1** [comment]
Thank you!

**Comment by ngeorgis** [comment]
Thank you, but could you clarify please on ADL-P GT2 ? 

Device ID 0x46A0 is in https://github.com/intel/compute-runtime/blob/8c930049375806136d758fd87cfdbb9cac1ec7e3/opencl/test/unit_test/gen12lp/adlp/linux/dll/device_id_tests_adlp.cpp but not in https://github.com/intel/compute-runtime/blob/21.46.21636/shared/source/dll/devices/devices_base.inl#L35
If ADL-P GT2 supported or not yet? 

Or may I should rebuild with SUPPORT_ADLP ?
