### ISSUE TITLE
`cl_khr_integer_dot_product` support

### ISSUE THREAD

**Issue by masahi** [intel/compute-runtime#482]
Hi, I'm looking forward to the availability of `cl_khr_integer_dot_product` extension released in OpenCL 3.0.8. Is this being planned?

**Comment by AdamCetnerowski** [comment]
Yes. I cannot provide an ETA, but this is in our near-term plans.

**Comment by JablonskiMateusz** [comment]
merged https://github.com/intel/compute-runtime/commit/dbd9b19b353f3619873fbba25dda3b060a0d9b37
