### ISSUE TITLE
[Question] Has latest repo supported DG2 platform?

### ISSUE THREAD

**Issue by heyu1** [intel/compute-runtime#485]
I ran it on DG2 (TGL-H) platform, but all failed.
And DG2 is not included in "Quality expectations", could you help to confirm this?
Thanks!

**Comment by JablonskiMateusz** [comment]
Hi @heyu1 , DG2 support has been initially enabled in the repository. Once it is validated and ready for external use, we’ll add it to the “Quality expectations” section.

**Comment by eero-t** [comment]
For this to work, you will need DG2 support also in kernel, and the compute-runtime dependencies (gmmlib / IGC).  In kernel case, you're going to need to use (PCI ID) force-probe option for quite a while.
