### ISSUE TITLE
L0 doc refers to unmaintained repositories

### ISSUE THREAD

**Issue by eero-t** [intel/compute-runtime#512]
This document: https://github.com/intel/compute-runtime/blob/master/level_zero/doc/DISTRIBUTIONS.md

Refers to COPR repo that can be used to get packages for several distros: https://copr.fedorainfracloud.org/coprs/jdanecki/intel-opencl/

But according to that package repo, and the Git repository used for providing its contents: https://github.com/JacekDanecki/neo-specs

It's not maintained any more, and the packages are several months old.  Please update the L0 document accordingly.

**Comment by JacekDanecki** [comment]
Together with information about external repositories, I've prepared PR: https://github.com/intel/compute-runtime/pull/511

**Comment by eero-t** [comment]
@JablonskiMateusz Yes, "DISTRIBUTIONS.md" is now gone => Closing.

Btw. Section headings in this L0 doc are broken (they are interpreted as list items  instead of headings): https://github.com/intel/compute-runtime/blob/master/level_zero/doc/BUILD.md

PS. Adding info from the PR also here, in case somebody else wonders where to get things now and finds this ticket:

> For Ubuntu, releases section of this github project should be sufficient. For other distros, the default channel to get the binaries should be repositories.intel.com (see instructions on https://dgpu-docs.intel.com/). We are aware that that release channel is currently lagging behind, the intention is to improve on it in the near future.
