### ISSUE TITLE
Any compute folks about to help with this OGL issue on intel HD3000?

### ISSUE THREAD

**Issue by ketxxx** [intel/compute-runtime#521]
One last long shot I need to take in making a true 64bit Win10 driver for the intel HD3000 IGP (if anyone wants a bit more insight into what I'm doing you can see the case I closed here; https://github.com/intel/compute-runtime/issues/518), it came to my attention yesterday that OpenGL support for the HD3000 in Win10 is completely broken, certainly a compatibility issue and one that seems to be more on Win10s side than it does the OGL DLLs as some people report having "full" OGL 3.1 support (despite the IGP being capable of OGL 3.3) via use of the MS Application Compatibility Tools but that workaround doesn't seem to work for everyone, or on later builds of W10 even with the ADK for W10 2004 builds and newer. So my question is; does anyone have OGL DLLs for HD3000 that are fully compatible with W10? I'm not even looking for something that brings the OGL spec back up to 3.1 just something thats far better than the MS generic driver that hobbles everyone with OGL 1.1 when the HD3000 driver is installed. Ironically with no HD3000 driver installed at all just running off the Basic Display Adapter driver W10 detects and defaults HD3000 to OGL 3.3 compatibility profile using Mesa 22.0 :)

Any assist would be greatly appreciated by anyone and everyone with intel HD3000 IGP! We just want to be able to use hardware H.264 encoding (my package has resolved that one) and be able to play stuff like Minecraft and do some PS1 emulation without OpenGL errors :o)

**Comment by eero-t** [comment]
Please close the ticket, this project OpenCL / OneAPI L0 driver, **not** OpenGL driver.

**Comment by ketxxx** [comment]
Well, that is unfortunate. I guess 70%~ functionality/compatibility is going to be as good as it gets for people with HD3000 IGPs which to be frank rankles us more than just a bit especially as HD4000 gets fully compatible W10 drivers despite it's announcement date only being 50 days after HD3000. Thanks anyway.
