### ISSUE TITLE
Checksum issue

### ISSUE THREAD

**Issue by leoheck** [intel/compute-runtime#525]
Hello 

Installing the latest version from here, 
https://github.com/intel/compute-runtime/releases/tag/22.10.22597

Saw that this file has some files/lines with wrong names (extensions):
https://github.com/intel/compute-runtime/releases/download/22.10.22597/ww10.sum

See the `.ddeb` on lines 4 and 6.
![image](https://user-images.githubusercontent.com/1277920/159053393-bc6957eb-0f5b-4b0e-9ec6-4d0981f8b44d.png)

Then the check fails
```bash
➜  neo sha256sum -c ww10.sum
intel-gmmlib_22.0.2_amd64.deb: OK
intel-igc-core_1.0.10409_amd64.deb: OK
intel-igc-opencl_1.0.10409_amd64.deb: OK
sha256sum: intel-level-zero-gpu-dbgsym_1.3.22597_amd64.ddeb: No such file or directory
intel-level-zero-gpu-dbgsym_1.3.22597_amd64.ddeb: FAILED open or read <========================
intel-level-zero-gpu_1.3.22597_amd64.deb: OK
sha256sum: intel-opencl-icd-dbgsym_22.10.22597_amd64.ddeb: No such file or directory
intel-opencl-icd-dbgsym_22.10.22597_amd64.ddeb: FAILED open or read <========================
intel-opencl-icd_22.10.22597_amd64.deb: OK
sha256sum: WARNING: 2 listed files could not be read
```

**Comment by Pookalton** [comment]
Maybe no one actually uses the checksums?...
That's a bit scary
I noticed this a few days ago too any decided not to install.

**Comment by leoheck** [comment]
Did you rename files to use the wrong extension `.ddeb` or did you update the `.sum` file with the right extension `.deb`?

**Comment by JablonskiMateusz** [comment]
Hi @leoheck could you just download ddeb files? They are included to release:
```
wget https://github.com/intel/compute-runtime/releases/download/22.10.22597/intel-level-zero-gpu-dbgsym_1.3.22597_amd64.ddeb
wget https://github.com/intel/compute-runtime/releases/download/22.10.22597/intel-opencl-icd-dbgsym_22.10.22597_amd64.ddeb
```

**Comment by wzmudat** [comment]
Issue fixed: https://github.com/intel/compute-runtime/releases/tag/22.10.22597
