### ISSUE TITLE
Typo: ExecutionEnivronment

### ISSUE THREAD

**Issue by tjaalton** [intel/compute-runtime#530]
git grep ExecutionEnivronment
IGC/AdaptorOCL/OCL/KernelAnnotations.hpp:struct ExecutionEnivronment
IGC/Compiler/CodeGenPublic.h:        iOpenCL::ExecutionEnivronment m_executionEnivronment = {};
IGC/VectorCompiler/igcdeps/src/cmc.cpp:  iOpenCL::ExecutionEnivronment &ExecEnv =

surely it's meant to be 'ExecutionEnvironment'?

**Comment by JablonskiMateusz** [comment]
hi @tjaalton 
please move this issue to https://github.com/intel/intel-graphics-compiler as mentioned structs are defined there

**Comment by tjaalton** [comment]
haha, oops..
