### ISSUE TITLE
Build error: >type ‘struct drm_i915_gem_create_ext’ violates the C++ One Definition Rule

### ISSUE THREAD

**Issue by ran-dall** [intel/compute-runtime#531]
I observed this build problem a few versions ago, and I was just able to forcibly turn off LTO to make it build; however, upon further inspection of merging the fix into the ebuild, Gentoo upstream suggested the root cause of the problem to be more serious...

```
>../compute-runtime-22.14.22890/third_party/uapi/drm/i915_drm.h:2951: error: >type ‘struct drm_i915_gem_create_ext’ violates the C++ One Definition Rule >[-Werror=odr]
> 2951 | struct drm_i915_gem_create_ext {
```

Ref 👉 https://bugs.gentoo.org/838241

🤷 Maybe related to or duplicate of 👉 https://github.com/intel/compute-runtime/issues/528

**Comment by JablonskiMateusz** [comment]
Hi @ran-dall. Thanks for reporting the issue. I've added this to our queue.

**Comment by ran-dall** [comment]
@ArchangeGabriel Thanks for confirming.
