### ISSUE TITLE
libigdgmm12 (= 22.1.2)

### ISSUE THREAD

**Issue by sagitt** [intel/compute-runtime#533]
can't download this lib in last release:

wget https://github.com/intel/compute-runtime/releases/download/22.16.22992/intel-gmmlib_22.0.2_amd64.deb
--2022-04-23 14:08:55--  https://github.com/intel/compute-runtime/releases/download/22.16.22992/intel-gmmlib_22.0.2_amd64.deb
Risoluzione di github.com (github.com)... 140.82.121.4
Connessione a github.com (github.com)|140.82.121.4|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 404 Not Found
2022-04-23 14:08:55 ERRORE 404: Not Found.

**Comment by ArturHarasimiuk** [comment]
@sagitt - thanks for feedback. I've corrected urls in release notes

**Comment by eero-t** [comment]
@sagitt Can you verify and close this?

**Comment by sagitt** [comment]
> @sagitt Can you verify and close this?

Works.
Thanks

**Comment by eero-t** [comment]
Thanks!
