### ISSUE TITLE
Level Zero: Image addressing modes mixed up

### ISSUE THREAD

**Issue by linehill** [intel/compute-runtime#534]
Image addressing modes `ZE_SAMPLER_ADDRESS_MODE_CLAMP` and `ZE_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER` are mixed up in Level Zero. On out-of-bounds image reads, the former mode returns zero (should return edge value) and the latter returns edge value (should return zero).

Test environment:
```
OS: Ubuntu 20.04.4 LTS
Package: level-zero
Version: 1.6.2+i643~u20.04
Device: Intel(R) HD Graphics 530 [0x1912]
```

**Comment by MaciejPlewka** [comment]
Hi @linehill we have already fixed this issue with this commit https://github.com/intel/compute-runtime/commit/6968bfdb33ebd2bfa1f7c22c0d9d432f9ec72353. So fix should be available in our driver after this release https://github.com/intel/compute-runtime/releases/tag/22.04.22286.

Please try with latest driver, and let us know if it works fine now.

**Comment by linehill** [comment]
Confirmed to work with the latest driver. Thanks.
