### ISSUE TITLE
Ivy Bridge and Haswell Missing

### ISSUE THREAD

**Issue by iamhumanipromise** [intel/compute-runtime#539]
OpenCL 2.0 used to be supported, and 2.1 with Beignet. This means that 3.0 is supported, correct? 

Why are these two missing?

**Comment by JablonskiMateusz** [comment]
Hi @iamhumanipromise 
Ivy Bridge and Haswell are supported by beignet driver. Please move the issue to their repo https://github.com/intel/beignet

**Comment by eero-t** [comment]
@JablonskiMateusz bug reporters cannot move bugs between projects (project owners may be be able to, as I've seen that done, but they probably would need to be admins on both projects, which I do not think to be the case here).

Bug reporter can close this bug, and file it correctly to beignet project. @iamhumanipromise, could you do that?

**Comment by JablonskiMateusz** [comment]
Closing the issue, please create an issue in beignet repo.

**Comment by iamhumanipromise** [comment]
Sorry I did not see this. Beignet project is nearing unmaintained status.
Request is compute-runtime project stop need for Beignet by integrating it
into compute-runtime project.

**Comment by eero-t** [comment]
> Sorry I did not see this. Beignet project is nearing unmaintained status. Request is compute-runtime project stop need for Beignet by integrating it into compute-runtime project.

@iamhumanipromise There's a reason why compute-runtime support started from the HW versions it did.  Older platforms are lacking HW support that compute-runtime relies on.  Like is the case also with Mesa Iris 3D driver, and intel media-driver Media driver.  They are not going to support platforms lacking HW the features they rely on (such as IVB or HSW).
