### ISSUE TITLE
Is there any plan to support old architectures like Haswell?

### ISSUE THREAD

**Issue by YijinLiu** [intel/compute-runtime#55]
Or do you expect users to use Beignet for old architectures?

**Comment by PiotrRozenfeld** [comment]
For Gen8+, NEO replaces Beignet.
For Gen7 (Ivy Bridge) and Gen7.5 (Haswell), Beignet remains the recommended legacy driver, NEO will never support these platforms.

**Comment by MichalMrozek** [comment]
Looks like question is answered.
