### ISSUE TITLE
Typos in zello_sysman.cpp

### ISSUE THREAD

**Issue by eero-t** [intel/compute-runtime#562]
```
$ git grep avalialbe
level_zero/tools/test/black_box_tests/zello_sysman.cpp:        return "NOT SUPPORTED MODE Engine avalialbe";
level_zero/tools/test/black_box_tests/zello_sysman.cpp:        return "NOT SUPPORTED MODE Engine avalialbe";
level_zero/tools/test/black_box_tests/zello_sysman.cpp:        return "NOT SUPPORTED MODE Engine avalialbe";
```
Bugs:
* avalialbe -> available
* None of these error messages are for engine modes, they are for:
  * engine flag types
  * temperature sensor types
  * engine group types

**Comment by saik-intel** [comment]
FIXED WITH PR # https://github.com/intel-innersource/drivers.gpu.compute.runtime/pull/14834#pullrequestreview-1125014492

**Comment by JablonskiMateusz** [comment]
change is merged https://github.com/intel/compute-runtime/commit/183d82b02161b43b9f6172e8feda38522def416e

**Comment by eero-t** [comment]
Looks good, thanks!
