### ISSUE TITLE
Is whiskey lake supported?

### ISSUE THREAD

**Issue by fig-shimooka** [intel/compute-runtime#574]
Looking at the list, I don't see whiskey lake in the list.
Can I use Kaby Lake instead?

**Comment by jandres742** [comment]
@fig-shimooka definitely. You can use KBL.

**Comment by AdamCetnerowski** [comment]
All Gen9 GPUs are supported, we simply donm't list derivates in the README. If you would like to check a specific device, please see these [instructions](https://github.com/intel/compute-runtime/blob/master/FAQ.md#how-can-i-check-that-my-specific-device-is-supported-by-the-driver).

**Comment by fig-shimooka** [comment]
解決しました
