### ISSUE TITLE
Broken link to installation on other OSes

### ISSUE THREAD

**Issue by artanokhov** [intel/compute-runtime#605]
Hello, folks
I've been looking at [your releases](https://github.com/intel/compute-runtime/releases) and found that link to other installation procedures is broken, because it leads to a missing file

>Other installation procedures are described [here](https://github.com/intel/compute-runtime/blob/master/DISTRIBUTIONS.md).
https://github.com/intel/compute-runtime/blob/master/DISTRIBUTIONS.md

**Comment by AdamCetnerowski** [comment]
Thank you for report. We will make sure that the release notes for the next release do not have this link.

**Comment by psidor99** [comment]
All broken links have been removed from releases.
