### ISSUE TITLE
Linux requirements for Arc support

### ISSUE THREAD

**Issue by maleadt** [intel/compute-runtime#610]
I just got an A770, and am trying to get Julia oneAPI support to work (which works with the Level Zero APIs), but I'm always running into a ZE_RESULT_ERROR_UNKNOWN when I try to `zeCommandQueueExecuteCommandLists`. I have a C reproducer in https://github.com/JuliaGPU/oneAPI.jl/issues/228#issuecomment-1403779896, and this fails both with my 22.43.24595 binaries as well as the ones packaged by Arch Linux. If I target the IGP that's also available on that system, everything works. Stracing my C reproducer reveals that the `DRM_IOCTL_I915_GEM_EXECBUFFER2` syscall returns EINVAL. Upgrading to Linux 6.2-rc5 fixes the issue.

Is this expected? Do we need such a bleeding-edge kernel for Level Zero to work on A770, or am I doing something wrong? FWIW, I'm not using a bleeding-edge linux-firmware, so GUC initialization still fails.

**Comment by AdamCetnerowski** [comment]
Yes, you need a 6.2-rc kernel version for correct Alchemist support.

**Comment by maleadt** [comment]
OK, that's clear. It would probably be good to add this to https://github.com/intel/compute-runtime/blob/master/FAQ.md#which-linux-versions-does-neo-support

**Comment by AdamCetnerowski** [comment]
We're completing our validation on the release candidates and intend to update the documentation once 6.2 is still released. 

Thank you for being an active community member.
