### ISSUE TITLE
global memory size issue

### ISSUE THREAD

**Issue by jinz2014** [intel/compute-runtime#624]
"clinfo" shows that the global memory size is about 243 MiB. Is there anything wrong with the installation ? Thanks.

OS: Ubuntu 22.04.2
Kernel version: 5.17.0-1020-oem

```
  Device Name                                     Intel(R) Graphics [0x56a0]
  Driver Version                                  22.49.25018.23
 Global memory size                              255012864 (243.2MiB)
  Max memory allocation                           127506432 (121.6MiB)
```

**Comment by jinz2014** [comment]
Any suggestions on troubleshooting ? Thanks.

**Comment by BA8F0D39** [comment]
@jinz2014 
Enable resizable bar on BIOS or try latest stable kernel 6.2.2

**Comment by jinz2014** [comment]
Thank you for your suggestions.
