### ISSUE TITLE
Issues with passing SoA 

### ISSUE THREAD

**Issue by pvelesko** [intel/compute-runtime#631]
Ran into this issue on discrete Intel GPUs for both OpenCL and Level Zero.

```
struct Data {
  int *A_d;
} typedef Data;
```

Passing in this struct right after allocation results in no data getting copied out of the GPU. The workaround is that I have to do a memset or a memcpy on the device memory before launching the kernel. Doesn't matter if the data is allocated device or shared. This workaround doesn't seem to work in iGPU I tested but works for dGPU. 

[firstTouch.zip](https://github.com/intel/compute-runtime/files/11017823/firstTouch.zip)

Reproducer attached - comment in main.cpp with a block of code to uncomment in order to get this test to pass.

**Comment by zzdanowicz** [comment]
Hi, 
In reproducer attached, you are passing USM pointer to the kernel by value and thus you are missing allocation residency.
There are two options:
1) Use explicit residency on your USM allocation: zeContextMakeMemoryResident (https://spec.oneapi.io/level-zero/latest/core/api.html#zecontextmakememoryresident)
2) Set kernel indirect access to USM device (USM type used in reproducer): zeKernelSetIndirectAccess (https://spec.oneapi.io/level-zero/latest/core/api.html#zekernelsetindirectaccess)

Option 1) consumes less memory but require manual eviction, option 2) assures residency for all USM allocations of a given type, but no need to worry for manual eviction.

**Comment by zzdanowicz** [comment]
In Level Zero all allocations are USM pointers.

**Comment by pvelesko** [comment]
@zzdanowicz using `zeKernelSetIndirectAccess` works on an Arc series GPUs but not on PVC. Is this known behavior?

**Comment by zzdanowicz** [comment]
We might have such problem on PVC, but we haven't have a report until now. Please, could you file new issue against `zeKernelSetIndirectAccess` on PVC and provide simple reproducer plus driver version you are experiencing the behavior.

**Comment by zzdanowicz** [comment]
On PVC as a W/A you might want to use explicit residency I have mentioned above if you need to have your application to be working on a platform.
