### ISSUE TITLE
Openvino benchmark app seg faulting when run through WSL container

### ISSUE THREAD

**Issue by avinashbhat09** [intel/compute-runtime#666]
Hello,

I constantly get segmentation fault while running openvino benchmark app from the docker container. Steps followed as per this weblink - https://community.intel.com/t5/Blogs/Tech-Innovation/Artificial-Intelligence-AI/Witness-the-power-of-Intel-iGPU-with-Azure-IoT-Edge-for-Linux-on/post/1382405

dmesg output:
[   87.077626] IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready
[   96.059328] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -22
[   96.060824] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -22
[   96.062197] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -22
[   96.063907] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -2
**[   96.141740] benchmark_app[930]: segfault at 5610b4508 ip 00007f302f086e92 sp 00007ffc406e5620 error 4 in libigdrcl.so[7f302eb1a000+67a000]**
[   96.141766] Code: 00 e9 f2 44 a9 ff 66 90 f3 0f 1e fa 48 8d 05 b5 9c 26 00 53 48 89 fb 48 83 c0 10 48 89 07 48 8b 7f 08 48 85 ff 74 21 48 8b 07 <48> 8b 50 40 48 3b 15 4b f6 26 00 75 19 48 8b 40 08 5b ff e0 66 2e
[   96.141780] potentially unexpected fatal signal 11.

Config:
WSL2 Ubuntu22.04
intel-igc-opencl_1.0.14062.11
intel-igc-core_1.0.14062.11

**Comment by JablonskiMateusz** [comment]
@avinashbhat09 could you retry on our latest release?
