### ISSUE TITLE
zeCommandListHostSynchronize throws unexpected error code

### ISSUE THREAD

**Issue by pvelesko** [intel/compute-runtime#670]
Saw this new feature and wanted to try it. 

Possible return codes:
[ZE_RESULT_SUCCESS](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1a3ea791bcf22ddfc1d413579b12c22767ae892446ebfef04994eaa45d020c528cd)

[ZE_RESULT_ERROR_UNINITIALIZED](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1a3ea791bcf22ddfc1d413579b12c22767aed109126c34c65188f22b5bdb6c4c37f)

[ZE_RESULT_ERROR_DEVICE_LOST](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1a3ea791bcf22ddfc1d413579b12c22767a1068b875393bd04173ce6d2810189890)

[ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1a3ea791bcf22ddfc1d413579b12c22767a92f42c5377d848e194d8c5cf37726c48)

[ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1a3ea791bcf22ddfc1d413579b12c22767a5bab92487a6c32ddc14770ca229ed6e5)

[ZE_RESULT_ERROR_INVALID_NULL_HANDLE](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1a3ea791bcf22ddfc1d413579b12c22767a21376db55e4a4577d2b527dfcd6bb381)

nullptr == hCommandList

[ZE_RESULT_NOT_READY](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1a3ea791bcf22ddfc1d413579b12c22767a10bf3dc545c8aa0b8602f0e1ffad0b00)

timeout expired

[ZE_RESULT_ERROR_INVALID_ARGUMENT](https://spec.oneapi.io/level-zero/latest/core/api.html#ze__api_8h_1a3ea791bcf22ddfc1d413579b12c22767a8cd1b74592e87a5e23410e3424de7f05)

handle does not correspond to an immediate command list

Actual result:

```
Using regular command list
Device   : Intel(R) Arc(TM) A380 Graphics
Type     : GPU
Vendor ID: 8086
#Queue Groups: 2
Launching Kernel
Kernel Launched
Closing Command List ... complete
Host Synchronize ...Error at zeCommandListHostSynchronize(cmdList, std::numeric_limits<uint64_t>::max()): main: 105
Exit with Error Code: 0x78000003
Error Description: ZE_RESULT_ERROR_UNSUPPORTED_FEATURE
terminate called without an active exception
[1]    98025 IOT instruction (core dumped)  ./driver
```

Driver Version                                  23.17.26241.22

**Comment by BartoszDunajski** [comment]
Hi,
zeCommandListHostSynchronize can be used only on immediate command lists.  According to attached log, you are using "regular" command list, which is not allowed.
You are right, error code should be different (ZE_RESULT_ERROR_INVALID_ARGUMENT), but this feature is still under development - this is why you see ZE_RESULT_ERROR_UNSUPPORTED_FEATURE. 

https://spec.oneapi.io/level-zero/latest/core/api.html#zecommandlisthostsynchronize 
"Synchronizes an immediate command list by waiting on the host for the completion of all commands previously submitted to it."

**Comment by pvelesko** [comment]
Opps, forgot to uncomment the line that enables imm lists. Just tested and it works. Keep it open to track the return code or close. Thanks. @BartoszDunajski
