### ISSUE TITLE
Delete me

### ISSUE THREAD

**Issue by soehrlein** [intel/compute-runtime#702]
.

**Comment by soehrlein** [comment]
Installing Ubuntu 23.10 (kernel 6.5.0-9), adding i915.force_probe=7d55, and then installing manually all of the *.deb files from the compute-runtime seems to work. I'm not sure why, and will at some point need to recompile a newer kernel, hopefully it continues to work with a 6.7/6.8-intel-next kernel.

Leaving this open momentarily to see if anyone might suggest what could have been wrong, then will close.

**Comment by thetick1234567890** [comment]
Hi,

I'm also am seeing no devices found with 6.8rc1 / rc 2 / rc3 Ubuntu mainline kernels.  The exact same hardware rebooted with 6.7.3 works just fine with opencl workloads.  I tried on two different old but supported iGPU ( Broadwell, Skylake) platforms.

Could you please try and run clinfo on a 6.8 kernel ?  I believe the issue with no found devices should be easy to reproduce.

**Comment by soehrlein** [comment]
Sorry it was difficult to find but if you search clinfo on my original post it contained the clinfo output from 6.8.

**Comment by thetick1234567890** [comment]
Hi,

@soehrlein I'm just a user like you.  I was just adding that I also was having issues with 6.8rc kernels.  My request above was for the Intel developers.
