### ISSUE TITLE
FAQ says implementation pending for cl_cache for Windows

### ISSUE THREAD

**Issue by apartridge** [intel/compute-runtime#703]
In the FAQ it states that Windows implementation of cl_cache is pending: https://github.com/intel/compute-runtime/blob/master/opencl/doc/FAQ.md#windows

It looks like in https://github.com/intel/compute-runtime/commit/d7d577ba4873b83cf57367529b49384c9748d510 the cl_cache feature is also enabled by default on Windows. I tested this feature (on both Linux and Windows) and it seems to be working fine.

So I think the FAQ document is just a bit out of date and can be updated?

**Comment by JablonskiMateusz** [comment]
Hi @apartridge
Thank you for catching that!
The feature is enabled for OCL by default, however L0 part is still in progress. We will update documentation once the feature is fully implemented.

**Comment by JablonskiMateusz** [comment]
Documentation updated: https://github.com/intel/compute-runtime/commit/9553dd1098ba624090541860d2de75eac2d1ee71
