### ISSUE TITLE
Error when zesInit() on windows client

### ISSUE THREAD

**Issue by sgwhat** [intel/compute-runtime#712]
Hi all,

I am trying to loading `"ze_intel_gpu64.dll"` on my windows client, but it doesn't work. I tried to loaded `libze_intel_gpu.so` on ubuntu before, and it works well. Could you please give me some advice to debug?

Thanks!

**Comment by sgwhat** [comment]
Here is my implementation:
```
void oneapi_init(char *oneapi_lib_path, oneapi_init_resp_t *resp) {
  ze_result_t ret;
  resp->err = NULL;
  const int buflen = 256;
  char buf[buflen + 1];
  int i;
  struct lookup {
    char *s;
    void **p;
  } l[] = {
      {"zesInit", (void *)&resp->oh.zesInit},
      {"zesDriverGet", (void *)&resp->oh.zesDriverGet},
      {"zesDeviceGet", (void *)&resp->oh.zesDeviceGet},
      {"zesDeviceGetProperties", (void *)&resp->oh.zesDeviceGetProperties},
      {"zesDeviceEnumMemoryModules",
       (void *)&resp->oh.zesDeviceEnumMemoryModules},
      {"zesMemoryGetProperties", (void *)&resp->oh.zesMemoryGetProperties},
      {"zesMemoryGetState", (void *)&resp->oh.zesMemoryGetState},
      {NULL, NULL},
  };

  resp->oh.handle = LOAD_LIBRARY(oneapi_lib_path, RTLD_LAZY);
  if (!resp->oh.handle) {
    char *msg = LOAD_ERR();
    snprintf(buf, buflen,
             "Unable to load %s library to query for Intel GPUs: %s\n",
             oneapi_lib_path, msg);
    free(msg);
    resp->err = strdup(buf);
    return;
  }

  // TODO once we've squashed the remaining corner cases remove this log
  LOG(resp->oh.verbose,
      "wiring Level-Zero management library functions in %s\n",
      oneapi_lib_path);

  for (i = 0; l[i].s != NULL; i++) {
    // TODO once we've squashed the remaining corner cases remove this log
    LOG(resp->oh.verbose, "dlsym: %s\n", l[i].s);

    *l[i].p = LOAD_SYMBOL(resp->oh.handle, l[i].s);
    if (!l[i].p) {
      resp->oh.handle = NULL;
      char *msg = LOAD_ERR();
      LOG(resp->oh.verbose, "dlerr: %s\n", msg);
      UNLOAD_LIBRARY(resp->oh.handle);
      snprintf(buf, buflen, "symbol lookup for %s failed: %s", l[i].s, msg);
      free(msg);
      resp->err = strdup(buf);
      return;
    }
  }

  ret = (*resp->oh.zesInit)(0);
  if (ret != ZE_RESULT_SUCCESS) {
    LOG(resp->oh.verbose, "zesInit err: %d\n", ret);
    UNLOAD_LIBRARY(resp->oh.handle);
    resp->oh.handle = NULL;
    snprintf(buf, buflen, "oneapi vram init failure: %d", ret);
    resp->err = strdup(buf);
  }

  return;
}
```

**Comment by sgwhat** [comment]
I also tried `"C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_59866568a5ee77ea\ze_loader.dll"`, but still got error:

![image](https://github.com/intel/compute-runtime/assets/38711238/5892680e-34ce-45b4-98c0-b53c1d4a5f78)

**Comment by JablonskiMateusz** [comment]
Hi @sgwhat  
do you see issue only with `zesInit`? Does `zeInit` work fine?

**Comment by sgwhat** [comment]
> Hi @sgwhat do you see issue only with `zesInit`? Does `zeInit` work fine?

No, it's failed.

**Comment by JablonskiMateusz** [comment]
is it problem with loading dll library or calling `zeInit`, or even loading anything in between?

**Comment by sgwhat** [comment]
> is it problem with loading dll library or calling `zeInit`, or even loading anything in between?

Just with calling `zeInit` after I loading `ze_loader.dll`.
https://github.com/felipeagc/ollama/blob/0c5346e55731d8d9466d18766cb98169edbecab5/gpu/gpu_info_oneapi.c#L61

**Comment by JablonskiMateusz** [comment]
you may build ze_loader.dll by yourself and see where it fails on loader side https://github.com/oneapi-src/level-zero

**Comment by eero-t** [comment]
> > is it problem with loading dll library or calling `zeInit`, or even loading anything in between?
> 
> Just with calling `zeInit` after I loading `ze_loader.dll` by `LoadLibrary`. https://github.com/felipeagc/ollama/blob/0c5346e55731d8d9466d18766cb98169edbecab5/gpu/gpu_info_oneapi.c#L61

Error in your backtrace is calling of a NULL pointer (PC=0).   Are you sure your log level is such that `LOG()` would show resolving errors, and that` LOAD_LIBRARY()` e.g. calls library initializers?

(AFAIK on Linux dynamic loader does that automatically, but I do not know about Windows mechanisms.)

PS. As general comments on `gpu_info_oneapi.c`, you could consider including Level-Zero loader `zes_api.h` header instead of copying subset of its values to `gpu_info_oneapi.h`.  (Maybe also consider using `sizeof()` for buffer sizes instead of separate `buflen` variable)

**Comment by sgwhat** [comment]
Hi, I have fixed this issue, thank you for your help! @eero-t @JablonskiMateusz
