### ISSUE TITLE
WARNING: 2 computed checksums did NOT match - for latest release, 1.3.28717

### ISSUE THREAD

**Issue by ionutnechita-intel** [intel/compute-runtime#719]
///# sha256sum -c ww09.sum
intel-igc-core_1.0.16238.4_amd64.deb: FAILED
intel-igc-opencl_1.0.16238.4_amd64.deb: FAILED
intel-level-zero-gpu-dbgsym_1.3.28717.12_amd64.ddeb: OK
intel-level-zero-gpu_1.3.28717.12_amd64.deb: OK
intel-opencl-icd-dbgsym_24.09.28717.12_amd64.ddeb: OK
intel-opencl-icd_24.09.28717.12_amd64.deb: OK
libigdgmm12_22.3.17_amd64.deb: OK
sha256sum: WARNING: 2 computed checksums did NOT match

Release: https://github.com/intel/compute-runtime/releases/tag/24.09.28717.12

**Comment by psidor99** [comment]
Fixed
