### ISSUE TITLE
Enable Xe KMD support by default

### ISSUE THREAD

**Issue by eero-t** [intel/compute-runtime#727]
The other Intel user-space GPU drivers already enable Xe KMD support by default in their latest releases:
* https://github.com/intel/media-driver/pull/1784
* https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/20418

Maybe OpenCL / L0 / Sysman driver should also do that?

**Comment by JablonskiMateusz** [comment]
Hi @eero-t 
Xe KMD support is enabled by default since https://github.com/intel/compute-runtime/commit/a2742492ab0cc84dd5a6512caaca4858c92caab8 
It is included in 24.13 release

**Comment by eero-t** [comment]
Verified with the latest tag (`24.17.29377.8`) using `drm-tip` kernel HEAD => Xe KMD is supported without it being explicitly enabled with a CMake option.
