### ISSUE TITLE
OpenCL on Minnowboard Max

### ISSUE THREAD

**Issue by gija92** [intel/compute-runtime#74]
Hi everyone, 

I'm using a Minnowboard Max with Intel Atom E3825 CPU and its GPU and just compiled and installed the ComputeRuntime (deb-file) on the platform.

But clinfo doesn't get me an OpenCL device like the GPU or CPU. I installed alle required libraries like, ocl-icd, ocl-header and ocl-icd-libopencl1 and also the compute runtime.

Is there any library I have to link somewhere else or am I missing some dependencies?

Thanks

**Comment by PiotrRozenfeld** [comment]
Could you please confirm this is your CPU?
https://ark.intel.com/products/78474/Intel-Atom-Processor-E3825-1M-Cache-1_33-GHz

This is Gen7 GPU that NEO does not support (we support Gen8 and beyond) - you'd need to use our legacy Beignet solution in your case.
