### ISSUE TITLE
How can I dump ISA?

### ISSUE THREAD

**Issue by wzw-intel** [intel/compute-runtime#75]
Hi,
In Beignet, I can set environment variable OCL_OUTPUT_ASM to "1" to dump Gen ISA. 

Is there any similar way for Neo to do that?

**Comment by alalek** [comment]
Are there some tools to extract ISA from OpenCL kernel binaries / files from "cl_cache" dir?

[Intel OpenCL SDK](https://software.intel.com/en-us/intel-opencl) has OpenCL kernel compiler (including ISA emit), but these tools are outdated and they are not able to work with NEO OpenCL.

**Comment by MichalMrozek** [comment]
Have you tried this ?
https://github.com/intel/opencl-intercept-layer/blob/master/docs/kernel_isa.md

**Comment by alalek** [comment]
Awesome! Thank you!

**Comment by MichalMrozek** [comment]
Looks like we can close this.

**Comment by wzw-intel** [comment]
@MichalMrozek Thank you very much for your hint.

@alalek Your links are very helpful, thank you.
