### ISSUE TITLE
Should zesDeviceEnumPowerDomains return 0 for Integrated GPUs?

### ISSUE THREAD

**Issue by roaa2ammar** [intel/compute-runtime#751]
Currently I am working with the Sysman API to measure power consumption and I am encountering an issue where zesDeviceEnumPowerDomains returns 0 consistently when running it on an integrated GPU (Device: Intel(R) UHD Graphics 770). However, when running on a discrete GPU it returns 1 (Device: Intel(R) Arc(TM) A770 Graphics).

I am working on Linux for both GPUs and driver version: 24.13.29138.29 for both.

Is this expected behaviour for integrated GPUs to return 0 power domains with zesDeviceEnumPowerDomains?

If so, is there an alternative way to measure the power consumption of integrated GPUs using the Level Zero API?

**Comment by eero-t** [comment]
> Is this expected behaviour for integrated GPUs to return 0 power domains with zesDeviceEnumPowerDomains?

Yes.  There's no separate power domain for iGPU.
 
> If so, is there an alternative way to measure the power consumption of integrated GPUs using the Level Zero API?

"UnCore" value reported by RAPL should be a good approximation for iGPU power usage.

AFAIK It is power consumption of other things on the die, other than the CPU cores, mainly iGPU + LLC.

LLC is shared with CPU cores, but GPU can utilize much more of that cache than any (single) CPU core, so normally LLC power usage included to "UnCore" could be though to be iGPU power usage too.

E.g. `turbostat` tool seems to show that as `GFXWatt`:
`# turbostat --show GFXWatt`

**Comment by saik-intel** [comment]
@roaa2ammar   we don't support power domains for IGPU hence it is returns NULL. Please use @eero-t  suggestions for exploring power values of IGPU and please close this issue as wont support
