### ISSUE TITLE
Cannot save cache to other directory on Windows using NEO_CACHE_DIR

### ISSUE THREAD

**Issue by CarlGao4** [intel/compute-runtime#762]
I set `NEO_CACHE_DIR` to another folder on Windows, and monitored the program with process monitor. I only saw that the program read the folder twice and no cache was written or read. However, if I remove this environment variable, cache was saved to `%localappdata%\NEO\neo_compiler_cache`. Driver version: `32.0.15.6081`
I tested using intel extension for pytorch.

---

No environment variable:
![image](https://github.com/user-attachments/assets/2236aa8f-2c11-4bac-bbbe-5d2cf16a0c15)

Previous files removed before environment variable set:
![image](https://github.com/user-attachments/assets/f4a88622-295d-429c-b9d0-4764f54ad835)
I've make sure that the path could be written in the latter test

**Comment by JablonskiMateusz** [comment]
Hi @CarlGao4  looks like an issue in reading attributes on our side. Fix in progress

**Comment by CarlGao4** [comment]
I'd like to ask when can I see this update in the graphic driver?

**Comment by JablonskiMateusz** [comment]
this will be included in 24.39 release

**Comment by CarlGao4** [comment]
Sorry for disturbing, but how can I know which version am I using on Windows?
