### ISSUE TITLE
No level-zero device in sycl-ls

### ISSUE THREAD

**Issue by jinz2014** [intel/compute-runtime#764]
After installing oneAPI 2024.2.0, sycl-ls does not show the level-zero device.  Thank you for explaining the issue.

[opencl:cpu][opencl:0] Intel(R) OpenCL, Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz OpenCL 3.0 (Build 0) [2024.18.6.0.02_160000]
[opencl:gpu][opencl:1] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A770 Graphics OpenCL 3.0 NEO  [23.17.26241.33]

```
intel-level-zero-gpu is already the newest version (1.3.26241.33-647~22.04).
level-zero is already the newest version (1.11.0-647~22.04).
intel-opencl-icd is already the newest version (23.17.26241.33-647~22.04).
```

**Comment by owlshrimp** [comment]
``
`libze1/noble 1.16.1-1build1 amd64
  oneAPI Level Zero -- share libraries
```
```
$ sudo apt-get install libze1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  libze1
0 upgraded, 1 newly installed, 0 to remove and 25 not upgraded.
Need to get 212 kB of archives.
After this operation, 1,320 kB of additional disk space will be used.
Get:1 http://ca.archive.ubuntu.com/ubuntu noble/universe amd64 libze1 amd64 1.16.1-1build1 [212 kB]
Fetched 212 kB in 0s (626 kB/s)
Selecting previously unselected package libze1:amd64.
(Reading database ... 359561 files and directories currently installed.)
Preparing to unpack .../libze1_1.16.1-1build1_amd64.deb ...
Unpacking libze1:amd64 (1.16.1-1build1) ...
Setting up libze1:amd64 (1.16.1-1build1) ...
Processing triggers for libc-bin (2.39-0ubuntu8.4) ...
```
doesn't seem to have done much of anything
