### ISSUE TITLE
Recent Intel compute runtime driver update doesnt detect igpu (number of platforms = 0 in clinfo)

### ISSUE THREAD

**Issue by SkyLLerGithub** [intel/compute-runtime#773]
OS: Arch Linux x86_64
CPU: intel i5 10210 u
GPU: Intel UHD Graphics 620

Recent driver update doesnt detect igpu. Verified by running clinfo
![image](https://github.com/user-attachments/assets/62dec94d-2eaa-44bf-88ba-b57e4e049ca3)

Downgrading works and device is detected in clinfo.
(here is version 24.35.30872.22-2)
![image](https://github.com/user-attachments/assets/26a3004a-713e-4953-93f7-efd6c9333c56)

I have 0 idea on how to troubleshoot this, any help is appreciated.

**Comment by nyanmisaka** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/intel-compute-runtime/-/issues/3

There's an issue ticket.

**Comment by SkyLLerGithub** [comment]
> https://github.com/intel/compute-runtime/blob/master/LEGACY_PLATFORMS.md
> 
> It would be best to file an issue on Archlinux as well to ask the maintainers to separate current and legacy platforms into two different packages.

Thank you.
