### ISSUE TITLE
Load gmmlib using soname

### ISSUE THREAD

**Issue by dvrogozh** [intel/compute-runtime#93]
@ArturHarasimiuk, @drprajap: FYI

Please, be aware that gmmlib got a fix for intel/gmmlib#28 which changes gmmlib install targets:
1. libigdgmm.so.<major>.<minor>.<patch>
2. libigdgmm.so.<major> -> libigdgmm.so.<major>.<minor>.<patch>
3. libigdgmm.so -> libigdgmm.so.<major>

libigdgmm.so still presents, but is a symbolic linker name which belongs to developer packages. Please, consider switching to load gmmlib with the soname (libigdgmm.so.<major>).

**Comment by ArturHarasimiuk** [comment]
Neo is using symbol GMM_UMD_DLL defined in file [GmmLibDllName.h](https://github.com/intel/gmmlib/blob/master/Source/GmmLib/inc/External/Common/GmmLibDllName.h). It is on GmmLib side to define proper name of shared library.
