### ISSUE TITLE
Where to get NEO devel package ?

### ISSUE THREAD

**Issue by neowong-taiwan** [intel/compute-runtime#94]
Hi,

Previous in legacy version of intel-opencl driver SRB5, it come with a devel package, contain several header files, like Khronos header files CL/*.h, and va_ext.h. I can see the Khronos header files and cl_va_api_media_sharing_intel.h (va_ext.h replacement?) in source tarball, wonder if the devel package can release with driver package too ? so we dont need to manually prepare those files.

thanks.

**Comment by JacekDanecki** [comment]
On Fedora you can install opencl-headers package which contains Khronos header
```
rpm -qf /usr/include/CL/cl_va_api_media_sharing_intel.h 
opencl-headers-2.2-1.20180306gite986688.fc27.noarch
```

On Ubuntu 18.04 it's in opencl-c-headers package:
```
dpkg -S /usr/include/CL/cl_va_api_media_sharing_intel.h 
opencl-c-headers: /usr/include/CL/cl_va_api_media_sharing_intel.h
```

In Arch it's in opencl-headers package:
```
pacman -Qo /usr/include/CL/cl_va_api_media_sharing_intel.h 
/usr/include/CL/cl_va_api_media_sharing_intel.h is owned by opencl-headers 2:2.2.20170516-1
```

**Comment by neowong-taiwan** [comment]
My system is Ubuntu 16.04, however, it's working fine with Ubuntu 18.04 package too, only need to copy cl_va_api_media_sharing_intel.h to va_ext.h, as OpenCV still refer it in va_intel.cpp.

Thanks for the help, I will close this issue.
